landing:
  enabled:     true
  with_layout: false
  lifetime:    3600

pawnStars:
  enabled:     true
  with_layout: false
  lifetime:    3600

americanPickers:
  enabled:     true
  with_layout: false
  lifetime:    3600

americanRestoration:
  enabled:     true
  with_layout: false
  lifetime:    3600

pickedOff:
  enabled:     true
  with_layout: false
  lifetime:    3600

franksPicks:
  enabled:     true
  with_layout: false
  lifetime:    300

mwba:
  enabled:     true
  with_layout: false
  lifetime:    3600

mwbaPetroliana:
  enabled:     true
  with_layout: false
  lifetime:    3600

mwbaRooseveltiana:
  enabled:     true
  with_layout: false
  lifetime:    3600

mwbaRailroadiana:
  enabled:     true
  with_layout: false
  lifetime:    3600
