_exploreCollections:
  enabled:     true
  with_layout: false
  lifetime:    300

_featuredWeek:
  enabled:     true
  with_layout: false
  lifetime:    300

_sidebarIndex:
  enabled:     true
  with_layout: false
  lifetime:    300
