_exploreCollections:
  enabled:     true
  with_layout: false
  lifetime:    600

_featuredWeek:
  enabled:     true
  with_layout: false
  lifetime:    600

_sidebarIndex:
  enabled:     true
  with_layout: false
  lifetime:    600
