all:
  stylesheets:
    - -frontend/responsive.css
    - frontend/modules/mycq.css
    - frontend/modules/seller.css

  javascripts:
    - jquery/columnview.js
    - jquery/tmpl.js
    - jquery/iframe-transport.js
    - jquery/load-image.js
    - jquery/canvas-to-blob.js
    - jquery/fileupload.js
    - jquery/fileupload-fp.js
    - jquery/fileupload-ui.js
    - jquery/autogrow-input.js

  components:
    slot1: [mycq, navigation]

storeSuccess:
  components:
    slot1: []
    sidebar_300:  [seller, sidebarStore]

signupSuccess:
  components:
    slot1: []
    footer: []

packagesSuccess:
  components:
    sidebar_300: [global, sidebar300]
