indexSuccess:
  stylesheets: [legacy/homepage.css, legacy/tags.css]
  components:
    slot_1: [general, indexSlot1]
  layout: layout-open

loginSuccess:
  stylesheets: [legacy/forms.css]
  components:
    sidebar: [general, sidebar]

landingSuccess:
  stylesheets: [legacy/aetn.css]

feedbackSuccess:
  stylesheets: [legacy/forms.css]
  layout: layout-minimal
