all:
  stylesheets: [frontend/modules/collection.css]
  javascripts: [jquery/ui.js]

indexSuccess:
  javascripts: [jquery/infinitescroll.js]
  components:
    sidebar_300: [collection, sidebar]

indexNoCollectibles:
  components:
    sidebar_300: [collection, sidebar]

collectibleSuccess:
  components:
    sidebar_300: [collection, sidebarCollectible]

  javascripts:
    - /assets/js/wysihtml5.js
    - /assets/js/bootstrap/wysihtml5.js
