all:
  stylesheets: [frontend/modules/collection.css]

indexSuccess:
  javascripts:
    - jquery/infinitescroll.js

  components:
    sidebar_300: [collection, sidebar]

indexNoCollectibles:
  components:
    sidebar_300: [collection, sidebar]

collectibleSuccess:
  javascripts: [jquery/rcarousel.js, jwplayer.js, jquery/expander.js]
  components:
    sidebar_300: [collection, sidebarCollectible]
