indexSuccess:
  javascripts: [jquery/infinitescroll.js]
  stylesheets: [frontend/collectibles.css]
  components:
    sidebar_300: [collection, sidebar]

indexNoCollectibles:
  components:
    sidebar_300: [collection, sidebar]

collectibleSuccess:
  components:
    sidebar_300: [collection, sidebarCollectible]
