all:
  stylesheets: [frontend/modules/collector.css]

indexSuccess:
  components:
    sidebar_300: [collector, sidebarIndex]

signupSuccess:
  components:
    footer: []

allFeedbackSuccess:
  components:
    sidebar_300: [collector, sidebarIndex]
