shopping_order:
  class: sfPropelORMRouteCollection
  options:
    model:                ShoppingOrder
    module:               shoppingOrder
    prefix_path:          /shoppingOrder
    column:               id
    with_wildcard_routes: true

shopping_order_export:
  url: /ShoppingOrder/export
  param: { module: ShoppingOrder, action: export }

ajax_typeahead:
  url:   /ajax/typeahead/:section/:page
  param: { module: ajax, action: typeAhead }
  requirements: { sf_method: [GET], sf_format: json }

wp_post:
  class: sfPropelORMRouteCollection
  options:
    model:                wpPost
    module:               wpPost
    prefix_path:          /wpPost
    column:               id
    with_wildcard_routes: true
    actions:              [list]

featured_weeks:
  class: sfPropelORMRouteCollection
  options:
    model:                Featured
    module:               featuredWeeks
    prefix_path:          /featuredWeeks
    column:               id
    with_wildcard_routes: true

collectible_for_sale_export:
  url: /collectibleForSale/export
  param: { module: collectibleForSale, action: export }

collectible_for_sale:
  class: icePropelRouteCollection
  options:
    model:                CollectibleForSale
    module:               collectibleForSale
    prefix_path:          /collectibleForSale
    column:               id
    with_wildcard_routes: true

comment:
  class: sfPropelORMRouteCollection
  options:
    model:                Comment
    module:               comments
    prefix_path:          /comments
    column:               id
    with_wildcard_routes: true

comment_ajax_update_content:
  url: /comments/update_content
  param: { module: comments, action: updateContent }
  requirements: { sf_method: [POST], sf_format: json }

promotion_transaction:
  class: sfPropelORMRouteCollection
  options:
    model:                PromotionTransaction
    module:               promotionTransaction
    prefix_path:          /promotionTransaction
    column:               id
    with_wildcard_routes: true

promotion:
  class: sfPropelORMRouteCollection
  options:
    model:                Promotion
    module:               promotion
    prefix_path:          /promotion
    column:               id
    with_wildcard_routes: true

package_transaction:
  class: sfPropelORMRouteCollection
  options:
    model:                PackageTransaction
    module:               packageTransaction
    prefix_path:          /packageTransaction
    column:               id
    with_wildcard_routes: true

package_transaction_add_extra_credits:
  url:                    /packageTransaction/:id/addExtraCredits
  class:                  sfPropelORMRoute
  options:
    model:                PackageTransaction
    type:                 object
    column:               id
  param:                  { module: packageTransaction, action: addExtraCredits }
  requirements:           { sf_method: [get, post] }


package:
  class: sfPropelORMRouteCollection
  options:
    model:                Package
    module:               package
    prefix_path:          /package
    column:               id
    with_wildcard_routes: true

playlist:
  class: icePropelRouteCollection
  options:
    model:                Playlist
    module:               playlists
    prefix_path:          /playlists
    column:               id
    with_wildcard_routes: true

private_message:
  class: icePropelRouteCollection
  options:
    model:                PrivateMessage
    module:               messages
    prefix_path:          /messages
    column:               id
    with_wildcard_routes: true

message_template:
  class: icePropelRouteCollection
  options:
    model:                PrivateMessageTemplate
    module:               messageTemplates
    prefix_path:          /messageTemplates
    column:               id
    with_wildcard_routes: true

content_category:
  class: icePropelRouteCollection
  options:
    model:                ContentCategory
    module:               contentCategory
    prefix_path:          /ContentCategories
    column:               id
    with_wildcard_routes: true

collection_category:
  class: icePropelRouteCollection
  options:
    model:                CollectionCategory
    module:               collectionCategories
    prefix_path:          /collectionCategories
    column:               id
    with_wildcard_routes: true

video_playlist:
  class: icePropelRouteCollection
  options:
    model:                VideoPlaylist
    module:               videoPlaylists
    prefix_path:          /videoPlaylists
    column:               id
    with_wildcard_routes: true

video:
  class: icePropelRouteCollection
  options:
    model:                Video
    module:               videos
    prefix_path:          /videos
    column:               id
    with_wildcard_routes: true

collectible:
  class: icePropelRouteCollection
  options:
    model:                Collectible
    module:               collectibles
    prefix_path:          /collectibles
    column:               id
    with_wildcard_routes: true

collection:
  class: icePropelRouteCollection
  options:
    model:                CollectorCollection
    module:               collections
    prefix_path:          /collections
    column:               id
    with_wildcard_routes: true

collector:
  class: icePropelRouteCollection
  options:
    model:                Collector
    module:               collectors
    prefix_path:          /collectors
    column:               id
    with_wildcard_routes: true

marketplace:
  url:   /marketplace
  param: { module: collectibleForSale, action: index }

item_offers:
  url:   /item/offers
  param: { module: collectibleForSale, action: itemOffers }

object_rating:
  url:   /ajax/set-rating/:class/:id
  param: { module: adminbar, action: rating }
  requirements: { class: "[^/]+", id: '\d+' }

ajax_object_rating:
  url:   /object/set-rating/:dimension/:class/:id
  param: { module: adminbar, action: rating }
  requirements: {dimension: "[^/]+", class: "[^/]+", id: '\d+' }

object_machine_tags:
  url:   /ajax/machine-tags/:class/:id
  param: { module: adminbar, action: machinetags }
  requirements: { class: "[^/]+", id: '\d+' }

# default rules

ga:
  url:   /ga
  param: { module: iceBackendModule, action: godAuth }

homepage:
  url:   /
  param: { module: iceBackendModule, action: dashboard }


# generic rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
