dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    logging_enabled:        true
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    web_debug:              false
    etag:                   false

all:
  .settings:
    default_timezone:       America/New_York
    charset:                utf-8
    no_script_name:         false
    cache:                  false

    enabled_modules:        [sfGuardAuth, sfGuardUser, sfGuardPermission, sfGuardGroup, iceBackendModule, iceMetaTagBackendModule, sent_email]
    standard_helpers:       [Partial, Cache, I18N, Text, iceAssets, iceJavascript, iceBackend, cqAssets, cqImages, cqJavascripts]
    sf_compat_10:           off

    # Form security secret (CSRF protection)
    csrf_secret:            09d149482b57e89b5a529d4e15ffa6623e01e6f6

    # Output escaping settings
    escaping_strategy:      false
    escaping_method:        ESC_SPECIALCHARS

    # Cache settings
    lazy_cache_key:         true

    # Logging
    logging_enabled:        false

  .actions:
    default_module:         iceBackendModule
    default_action:         dashboard

    error_404_module:       iceBackendModule
    error_404_action:       error404

    login_module:           iceBackendModule
    login_action:           signIn

    secure_module:          iceBackendModule
    secure_action:          secure
