default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: "chrome=1;IE=edge"

  metas:
    title:        "Backend - Collectors Quest"
    robots:       noindex, nofollow

  stylesheets:    [backend/default.css]
  javascripts:
    - backend/default.js

  has_layout:     true
  layout:         layout
