default:
  http_metas:
    content-type: text/html
    X-UA-Compatible: "chrome=1;IE=edge"

  metas:
    title:        "Backend - Collectors Quest"
    robots:       noindex, nofollow

  ## Stylesheets and Javascripts are forbidden to be defined here!
  ## Please use modules/iceBackendModule/templates/_head.php
  ##
  # stylesheets:
  # javascripts:

  has_layout:     true
  layout:         layout
