generator:
  class: IcePropelGenerator
  param:
    model_class:           Comment
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              Comment
    plural:                Comments
    route_prefix:          comment
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        author:      { label: Author }
        list_body:   { label: Comment }
        created_at:  { label: "Date & Time" }
        model_object:     { label: Comment Target }

      list:
        title:  Comments
        display:  [_model_object, body, author_name, author_email, ip_address, created_at]
        sort:  [created_at, desc]

        actions: {}
        object_actions:
          block_ip:    { label: 'Block IP',    action: blockIp }
          block_email: { label: 'Block Email', action: blockEmail }
          _delete:  { confirm: "Are you sure you want to delete this comment?" }

      filter:
        display: [subject, body]
        fields:
          subject:
            widgetOptions: { with_empty: false }

      form:
        class: BackendCommentForm
