<?php

require 'lib/model/marketplace/om/BaseShoppingPaymentPeer.php';

class ShoppingPaymentPeer extends BaseShoppingPaymentPeer
{
  const PAYPAL_TRANSACTION_ID = 'PAYPAL.TRANSACTION_ID';
  const PAYPAL_STATUS = 'PAYPAL.STATUS';
  const PAYPAL_SENDER_IDENTIFIER_FIELDS = 'PAYPAL.SENDER_IDENTIFIER_FIELDS';
  const PAYPAL_SENDER_EMAIL = 'PAYPAL.SENDER_EMAIL';
  const PAYPAL_RECEIVERS = 'PAYPAL.RECEIVERS';
  const PAYPAL_PAY_REQUEST_FIELDS = 'PAYPAL.PAY_REQUEST_FIELDS';
  const PAYPAL_PAY_KEY = 'PAYPAL.PAY_KEY';
  const PAYPAL_PAYMENT_DETAILS = 'PAYPAL.PAYMENT_DETAILS';
  const PAYPAL_CLIENT_DETAILS_FIELDS = 'PAYPAL.CLIENT_DETAILS_FIELDS';
  const PAYPAL_ACCOUNT_IDENTIFIER_FIELDS = 'PAYPAL.ACCOUNT_IDENTIFIER_FIELDS';
  const PAYPAL_ERROR = 'PAYPAL.ERROR';
}
