_indexCarousel:
  enabled:     true
  with_layout: false
  lifetime:    3600

_sidebarIndex:
  enabled:     true
  with_layout: false
  lifetime:    3600

index:
  enabled:     true
  with_layout: false
  lifetime:    600
