indexSuccess:
  javascripts:
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js

  components:
    slot1: [general, indexCarousel]
    sidebar_180: [general, indexSidebar]

countdownSuccess:
  has_layout: false
