indexSuccess:
  javascripts:
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js
    - jquery/roundabout-shapes.js

  components:
    slot1: [general, indexCarousel]
    sidebar_180: [general, indexSidebar]
