all:
  stylesheets: [frontend/modules/general.css]

indexSuccess:
  stylesheets: [frontend/modules/homepage.css]
  javascripts:
    - jquery/masonry.js
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js

  components:
    breadcrumbs: []
    slot1: [general, indexCarousel]

indexMobile:
  stylesheets: [frontend/modules/homepage.css]
  javascripts:
    - jquery/masonry.js
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js

  components:
    breadcrumbs: []
    slot1: [general, indexCarousel]

indexIndependenceDay:
  stylesheets: [frontend/modules/homepage.css]
  javascripts:
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js

  components:
    breadcrumbs: []
    slot1: [general, indexCarousel]
    sidebar_160: [general, sidebarIndex]

loginSuccess:
  components:
    footer: []

recoverPasswordSuccess:
  components:
    sidebar_300: [global, sidebar300]

feedbackSuccess:
  layout: layout-minimal

error404Success:
  components:
    sidebar_160: [general, sidebarIndex]

startPageSuccess:
  components:
    footer: []
