all:
  stylesheets: [frontend/modules/general.css]

indexSuccess:
  stylesheets: [frontend/modules/homepage.css]
  javascripts:
    - jquery/masonry.js
    - jquery/easing.js
    - jquery/event.drag.js
    - jquery/event.drop.js
    - jquery/roundabout.js

  components:
    breadcrumbs: []
    slot1: [general, indexCarousel]
    sidebar_160: [general, sidebarIndex]

countdownSuccess:
  has_layout: false

feedbackSuccess:
  layout: layout-minimal
