all:
  stylesheets: [frontend/modules/marketplace.css]

indexSuccess:
  components:
    sidebar_300: [marketplace, sidebarIndex]

browseSuccess:
  components:
    sidebar_300: [marketplace, sidebarIndex]

categoriesSuccess:
  components:
    sidebar_300: [marketplace, sidebarCategories]
