all:
  stylesheets: [frontend/modules/marketplace.css]

indexSuccess:
  components:
    sidebar_300: [marketplace, sidebarIndex]
    slot2: [marketplace, indexSlot2]

browseSuccess:
  components:
    sidebar_300: [marketplace, sidebarBrowse]

categoriesSuccess:
  components:
    sidebar_300: [marketplace, sidebarCategories]
