landing:
  enabled:     false
  with_layout: false
  lifetime:    3600

pawnStars:
  enabled:     false
  with_layout: false
  lifetime:    3600

americanPickers:
  enabled:     false
  with_layout: false
  lifetime:    3600
