all:
  stylesheets:
    - frontend/modules/aetn.css
    - frontend/modules/collections.css

americanPickersSuccess:
  components:
    sidebar_300: [aent, sidebarAmericanPickers]

pawnStarsSuccess:
  components:
    sidebar_300: [aent, sidebarPawnStars]

pickedOffSuccess:
  components:
    sidebar_300: [aent, sidebarPickedOff]

storageWarsSuccess:
  components:
    sidebar_300: [aent, sidebarStorageWars]

collectibleSuccess:
  javascripts: [jwplayer.js]
  components:
    sidebar_300: [aent, sidebarCollectible]
