all:
  stylesheets: [frontend/modules/collections.css]

americanPickersSuccess:
  components:
    sidebar_300: [aent, sidebarAmericanPickers]

pawnStarsSuccess:
  components:
    sidebar_300: [aent, sidebarPawnStars]

collectibleSuccess:
  components:
    sidebar_300: [aent, sidebarPawnStarsBrandItem]
