generator:
  class: IcePropelGenerator
  param:
    model_class:           PackageTransaction
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              PackageTransaction
    plural:                PackageTransactions
    route_prefix:          package_transaction
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        collector: { label: Seller }
        package_price: { label: Price }
        expiry_date: { label: Expiry Date }
        payment_status: { label: Status }
        created_at: { label: 'Order Date' }

      list:
        title: Package Transactions
        display: [collector, package_name, payment_status, credits, package_price, expiry_date, created_at]
        hide: [id]
        sort: [id, desc]
        object_actions:
          addExtraCredits:  { label: "Add extra credits to seller", action: addExtraCredits }
        batch_actions: { }
        actions: { }

      filter:
        class: BackendPackageTransactionFormFilter
        display: [collector_id, package_id]

      form: ~
      edit: ~
      new:
        actions:  { _list: ~, _save: ~ }
