# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class:   sfMonologLogger
    param:
      level:   err
      handlers:
        mail:
          type:         fingers_crossed
          action_level: crit
          handler:      buffered
        buffered:
          type:    buffer
          handler: swift
        swift:
          type:       swift_mailer
          from_email: no-reply@collectorsquest.com
          to_email:   developers@collectorsquest.com
          subject:    '[Monolog] An Error Occurred!'
          level:      debug

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  storage:
    class: cqSessionStorage
    param:
      session_name: frontend

  user:
    class: cqFrontendUser
    param:
      timeout:         86400
      logging:         %SF_LOGGING_ENABLED%
      use_flash:       true
      default_culture: %SF_DEFAULT_CULTURE%

  logger:
    class: sfAggregateLogger
    param:
      level: debug
      loggers:

        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug

        sf_file_debug:
          class: cqMonologLogger
          param:
            level:  err
            handlers:
              streamed:
                type:  stream
                path:  %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
                level:  debug
                bubble: true
#              main:
#                type:  fingers_crossed
#                action_level:  crit
#                handler:  grouped
#              grouped:
#                type:  group
#                members:  [streamed, firefox]
#              streamed:
#                type:  stream
#                path:  %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
#                level:  debug
#              firefox:
#                type:  fire_php
