test:
  logger:
    class: sfNoLogger
    param:
      loggers: ~

  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none


dev:
  logger:
    class: sfAggregateLogger
    param:
      level: debug
      loggers:

        sf_web_debug:
          class: sfWebDebugLogger
          param:
            level: debug
            condition:       %SF_WEB_DEBUG%
            xdebug_logging:  false
            web_debug_class: sfWebDebug

        sf_file_debug:
          class: sfNoLogger


all:
  mailer:
    class: cqMailer
    param:
      delivery_strategy: single_address
      delivery_address:  developers@collectorsquest.com
      charset: UTF-8
      transport:
        class: Swift_SmtpTransport
        param:
          host: smtp.gmail.com
          port: 465
          username: no-reply@collectorsquest.com
          password: gHnyU7wZLtYf3n
          encryption: tls

  routing:
    class: cqPatternRouting
    param:
      generate_shortest_url: true
      extra_parameters_as_query_string: true

  response:
    class: cqWebResponse

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  storage:
    class: cqSessionStorage
    param:
      session_name: frontend

  user:
    class: cqFrontendUser
    param:
      timeout:         86400
      logging:         %SF_LOGGING_ENABLED%
      use_flash:       true
      default_culture: %SF_DEFAULT_CULTURE%

  logger:
    class: sfNoLogger
    param:
      loggers: ~
