all:
  pages: ~
  features:
    shopping_cart: false
    shopping_checkout_help: false
    mycq_homepage: false
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false

next:
  pages: ~
  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: false
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false

dev:
  pages: ~
  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
