all:
  pages: ~
  features:
    shopping_cart: false
    mycq_marketplace: false

next:
  pages: ~
  features:
    shopping_cart: false
    mycq_marketplace: false

dev:
  pages: ~
  features:
    shopping_cart: true
    mycq_marketplace: true
