all:
  pages:
    marketplace_categories: false
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true
    holiday_marketplace: false

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true
<<<<<<< HEAD
=======
    machine_tags: false
>>>>>>> 6e592d63940e73e558a83e7f87c18b75ea60394e

next:
  pages:
    marketplace_categories: false
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true
    holiday_marketplace: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true
<<<<<<< HEAD
=======
    machine_tags: true
>>>>>>> 6e592d63940e73e558a83e7f87c18b75ea60394e

dev:
  pages:
    marketplace_categories: true
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true
    holiday_marketplace: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true
<<<<<<< HEAD
=======
    machine_tags: true
>>>>>>> 6e592d63940e73e558a83e7f87c18b75ea60394e
