all:
  pages: ~
  features:
    shopping_cart: false
    mycq_homepage: false
    mycq_marketplace: false
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: false
    collectible_shipping: false

next:
  pages: ~
  features:
    shopping_cart: false
    mycq_homepage: false
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: true
    collectible_shipping: false

dev:
  pages: ~
  features:
    shopping_cart: true
    mycq_homepage: false
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: false
    mycq_profile_addresses: true
    collectible_shipping: false
