all:
  pages:
    holiday_marketplace: true
    marketplace_categories: false
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_collectible_tax: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    expose_collection_categories: false
    expose_market_categories: false
    collectible_for_sale_related: true

stg:
  pages: []
  features: []

next:
  pages:
    holiday_marketplace: true
    marketplace_categories: false
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_collectible_tax: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    expose_collection_categories: false
    expose_market_categories: false
    collectible_for_sale_related: true

dev:
  pages:
    holiday_marketplace: true
    marketplace_categories: true
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_collectible_tax: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: true
    mycq_profile_addresses: false
    expose_collection_categories: false
    expose_market_categories: false
    collectible_for_sale_related: true
