all:
  pages:
    marketplace_categories: false
    aetn_picked_off: false

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: true
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false

next:
  pages:
    marketplace_categories: false
    aetn_picked_off: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: true
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false

dev:
  pages:
    marketplace_categories: true
    aetn_picked_off: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_seller_pay: true
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
