all:
  pages:
    marketplace_categories: false
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true

next:
  pages:
    marketplace_categories: false
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true

dev:
  pages:
    marketplace_categories: true
    aetn_picked_off: true
    aetn_american_restoration: true
    mycq_incomplete: true
    aetn_mwba: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true
