all:
  pages:
    aetn_picked_off: true
    aetn_american_restoration: true
    aetn_franks_picks: false
    aetn_mwba: true
    holiday_marketplace: false
    marketplace_categories: false
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true

next:
  pages:
    aetn_picked_off: true
    aetn_american_restoration: true
    aetn_franks_picks: true
    aetn_mwba: true
    holiday_marketplace: true
    marketplace_categories: false
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true

dev:
  pages:
    aetn_picked_off: true
    aetn_american_restoration: true
    aetn_franks_picks: true
    aetn_mwba: true
    holiday_marketplace: false
    marketplace_categories: true
    mycq_incomplete: true

  features:
    shopping_cart: true
    shopping_checkout_help: false
    mycq_homepage: true
    mycq_marketplace: true
    mycq_wanted: false
    mycq_profile_addresses: false
    collectible_shipping: true
    collectible_allow_no_shipping: true
    independence_day: false
    expose_collection_categories: true
    expose_market_categories: true
