seo:
  _config:
    separator: ' | '
    appendTitle: ''

  _blog:
    index:
      title: Collectors' Blog | News & Commentary from the Collector Community
      description: |
        Get the latest from the world of collectibles, vintage items, antique figurines,
        sports memorabilia and more at the Collectors Quest blog.

  general:
    index:
      title: Buy Sell Show | Antiques, Collectibles, Vintage Items | Collectors Quest
      description: |
        Join Collectors Quest to buy, sell, trade & show off your amazing collections,
        from antiques to collectibles, vintage to modern. See what other people collect!

  aent:
    pawnStars:
      title: Pawn Stars | TV Show Collectibles | Collectors Quest
      description: |
        CollectorsQuest.com gives you an exclusive look at the Pawn Stars Collectibles.
        See these and other TV Show Collectibles.

    americanPickers:
      title: American Pickers | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the American Pickers collection.
        CollectorsQuest.com gives you an inside look at the American Pickers collectibles.

    pickedOff:
      title: Picked Off | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the Picked Off collection.
        CollectorsQuest.com gives you an inside look at the Picked Off collectibles.

    # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11828067-history-a-e
    collectibleFixedMatching:
      model: true
      title:
        - %Name% | Collectors Quest
        - %Name% - %Collection% | Collectors Quest
      description:
        - %Description%
        - %Description% | %TagString%

    collectible:
      model: true
      title:
        - %Name% | Collectors Quest
        - %Name% - %Collection% | Collectors Quest
      description:
        - %Description%
        - %Description% | %TagString%

  categories:
    index:
      title: Browse Antique, Collectible & Vintage Items | Collectors Quest
      description: |
        Browse collectible, vintage & antique items on display at Collectors Quest.
        Share, interact, and show off your own collections!

    category:
      model: true
      title:
        - %Name% | Collectors Quest
        - %Name% Collections | Collectors Quest
        - %Name% Antique Collectible & Vintage | Collectors Quest
      description: |
        Browse collectible, vintage and antique items on Collectors Quest,
        like these %Name% items, posted by trusted sellers and passionate collectors!

  collections:
    title: Unique Antique, Collectible & Vintage Items | Collectors Quest
    description: |
      Browse our amazing collections of antique, vintage & collectible items
      from passionate collectors around the world.

  # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11746674-collection-page
  collection:
    index:
      model: true
      title:
        - %Name%
        - %Name% | Collectors Quest
        - %Name% by %Collector%
        - %Name% by %Collector% | Collectors Quest
        - %Name% - %TagString% | Collectors Quest
        - %Name% by %Collector% - %TagString%
        - %Name% by %Collector% - %TagString% | Collectors Quest
      description:
        - %Description%
        - %Description% | %TagString%
        - %Description% | From %ContentCategory% | %TagString%

    # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11739468-collectible-product
    collectible:
      model: true
      title:
        - %Name%
        - %Name% | Collectors Quest
        - %Name% by %Collector% | Collectors Quest
        - %Name% - %Collection% | Collectors Quest
        - %Name% - %Collection% by %Collector%
        - %Name% - %Collection% by %Collector% | Collectors Quest
      description:
        - %Description%
        - %Description% | %Name%
        - %Description% | %Name% from %Collection%
        - %Description% | %Name% from %Collection% by %Collector%
        - %Description% | %Name% from %Collection% by %Collector% | %TagString%

    # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11828067-history-a-e
    aentCollectibleFixedMatching:
      model: true
      title:
        - %Name% | Collectors Quest
        - %Name% - %Collection% | Collectors Quest
      description:
        - %Description%
        - %Description% | %TagString%

  # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11749079-collector-page
  collector:
    index:
      model: true
      title:
        - %DisplayName% | Collectors Quest
        - %DisplayName%’s Collectibles | Collectors Quest
        - %DisplayName%’s Collectibles | Buy & Sell on Collectors Quest

    signup:
      title: Buy and Sell Collectibles Online | Sign Up at CollectorsQuest.com
      description: |
        Sign up to sell or buy collectibles online.
        CollectorsQuest.com provides a unique marketplace for buying and selling collectibles online.

  collectors:
    index:
      title: Newest Collectors & Sellers | Collectors Quest
      description: |
        Check out the newest members on Collectors Quest! Show off your antique,
        collectible and vintage items, meet other collectors and buy, sell or trade with others.

  marketplace:
    index:
      title: Buy & Sell Antiques, Collectibles & Vintage Items | Collectors Quest
      description: |
        Browse our amazing collections of antique, vintage & collectible items
        from passionate collectors around the world.

    browse:
      model: true
      title:
        - %Name% | Collectors Quest
        - %Name% - Marketplace | Collectors Quest
        - Buy %Name% - Marketplace | Collectors Quest
      description:
        - Buy, sell & trade on Collectors Quest! Find %Name% posted by passionate collectors and trusted sellers.
        - Buy and sell antique, collectible & vintage items on Collectors Quest! Find %Name% posted by passionate collectors and trusted sellers.

    categories:
      title: Buy Antique Collectible & Vintage Marketplace Items | Collectors Quest
      description: |
        Find the collectible, vintage or antique item you’ve been looking for from trusted
        sellers in the Collectors Quest marketplace.

  collectibles:
    collectorList:
      model: true
      title: Collectibles by %DisplayName% | Collectors Quest

  misc:
    guideToCollecting:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.

    guideDownload:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.
