seo:
  _config:
    separator: ' | '
    appendTitle: ''

  _blog:
    index:
      title: Collectors' Blog | News & Commentary from the Collector Community
      description: Get the latest from the world of collectibles, vintage items, antique figurines, sports memorabilia and more at the Collectors' Quest blog.

  aetn:
    pawnStars:
      title: Pawn Stars Collectibles | TV Show Collectibles | Collectors Quest
      description: CollectorsQuest.com gives you an exclusive look at the Pawn Stars Collectibles. See these and other TV Show Collectibles.

    americanPickers:
      title: American Pickers Collection | TV Show Collectibles | Collectors Quest
      description: Check out these collectors items from the American Pickers Collection. CollectorsQuest.com gives you an inside look at the American Pickers collection.

  categories:
    index:
      title: Explore Our Endless Collection of Collectibles | Category Listing
      description: We have unique vintage items such as antique figurines and political memorabilia. Browse over 10,000 unique vintage antiques and collectibles today!

    category:
      title: Collectible %Name% | Collectible and Antique %Name%
      description: CollectorsQuest.com is the place to browse antique %Name%. Our sellers are serious about their interest in antique and collectible %Name%.
      keywords: %Name%
      model: true

  collections:
    title: Collectors Items | Find Unique Vintage Collectibles and Antiques
    description: CollectorsQuest.com has unique collectors items from  every era. Find unique vintage collectibles and antiques sold by trusted buyers.

  collection:
    collectible:
      title: %Name%
      model: true

  collector:
    signup:
      title: Buy and Sell Collectibles Online | Sign Up at CollectorsQuest.com
      description: Sign up to sell or buy collectibles online. CollectorsQuest.com provides a unique marketplace for buying and selling collectibles online.

  general:
    index:
      title: Collectors Selling Collectibles and Antiques | CollectorsQuest.com
      description: Collectors' Quest is interactive community and marketplace for collectors. Showcase your collections, meet other collectors and buy, sell or trade.

  marketplace:
    index:
      title: Collectibles & Antiques for Sale | Collectors' Quest
      description: CollectorsQuest.com is a trusted source to buy antiques and collectibles online. Our experienced collectors sell an amazing array of collections online.

    categories:
      title: Collectors | Buy Collectors Items in Our Marketplace
      description: CollectorsQuest.com is the leading online source for collectors to buy or sell collectibles. Buy unique vintage collectors items in our marketplace.

