seo:
  _config:
    separator: ' | '
    appendTitle: ''

  _blog:
    index:
      title: Collectors' Blog | News & Commentary from the Collector Community
      description: |
        Get the latest from the world of collectibles, vintage items, antique figurines,
        sports memorabilia and more at the Collectors Quest blog.

  general:
    index:
      title: Buy Sell Show | Collectibles, Antiques, Vintage Items | Collectors Quest
      description: |
        Join Collectors Quest to buy, sell, trade & show off your amazing collections,
        from antiques to collectibles, vintage to modern. See what other people collect!

  aent:
    pawnStars:
      title: Pawn Stars Collectibles | TV Show Collectibles | Collectors Quest
      description: |
        CollectorsQuest.com gives you an exclusive look at the Pawn Stars Collectibles.
        See these and other TV Show Collectibles.

    americanPickers:
      title: American Pickers Collection | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the American Pickers Collection.
        CollectorsQuest.com gives you an inside look at the American Pickers collection.

    collectible:
      model: true
      title: %Name% | %Collection%
      description: %Description%

    collectibleFixedMatching:
      model: true
      title: %Name% | %Collection%
      description: %Description%

  categories:
    index:
      title: Browse Antique, Collectible & Vintage Items | Collectors Quest
      description: |
        Browse collectible, vintage & antique items on display at Collectors Quest.
        Share, interact, and show off your own collections!

    category:
      model: true
      title: Collectible %Name% | Collectible and Antique %Name%
      description: |
        CollectorsQuest.com is the place to browse antique %Name%.
        Our sellers are serious about their interest in antique and collectible %Name%.
      keywords: %Name%

  collections:
    title: Unique Collectible, Vintage & Antique Items | Collectors Quest
    description: |
      Browse our amazing collections of antique, vintage & collectible items
      from passionate collectors around the world.

  collection:
    index:
      model: true
      title:
        - %Name%
        - %Name% | Collectors Quest
        - %Name% - %TagString% | Collectors Quest
      description:
        0: %Description%
        1: %Description% | From: %Collector%

    collectible:
      model: true
      title: %Name% | %Collection%
      description: |
        Collectors are selling collectible items such as this %Collection%.
        CollectorsQuest.com is the place to find %Name%, collectible items and more.

  collector:
    index:
      model: true
      title: Items for Sale by %DisplayName% | Buy Vintage Collectibles
      description: |
        CollectorsQuest.com is the best place to find %AboutWhatYouCollect% and items for sale.
        Find collectors selling %AboutWhatYouCollect%.

    signup:
      title: Buy and Sell Collectibles Online | Sign Up at CollectorsQuest.com
      description: |
        Sign up to sell or buy collectibles online.
        CollectorsQuest.com provides a unique marketplace for buying and selling collectibles online.

  marketplace:
    index:
      title: Buy & Sell Collectibles, Antiques & Vintage Items | Collectors Quest
      description: |
        Browse our amazing collections of antique, vintage & collectible items
        from passionate collectors around the world.

    browse:
      model: true
      title: Collectable %Name% | Vintage Collectable %Name%
      description: |
        Buy, sell and trade vintage collectable %Name%.
        Browse over %countCollections% collectible %Name% in the CollectorsQuest.com marketplace.

    categories:
      title: Buy Collectible Vintage & Antique Marketplace Items | Collectors Quest
      description: |
        Find the collectible, vintage or antique item you’ve been looking for from trusted
        sellers in the Collectors Quest marketplace.

  collectibles:
    collectorList:
      model: true
      title: Collectibles by %DisplayName% | Collectors Quest

  misc:
    guideToCollecting:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.

    guideDownload:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.
