seo:
  _config:
    separator: ' | '
    appendTitle: ''

  _blog:
    index:
      title: Collectors' Blog | News & Commentary from the Collector Community
      description: |
        Get the latest from the world of collectibles, vintage items, antique figurines,
        sports memorabilia and more at the Collectors Quest blog.

  general:
    index:
      title: Buy Sell Show | Antiques Collectibles Vintage Items | Collectors Quest
      description: |
        Join Collectors Quest to buy, sell, trade & show off your amazing collections,
        from antiques to collectibles, vintage to modern. See what other people collect!

    recoverPassword:
      title: Forgot your username and/or password? | Collectors Quest

    login:
      title: Sign in to Collectors Quest | Use Facebook Twitter Google WordPress

  aetn:
    pawnStars:
      title: Pawn Stars | TV Show Collectibles | Collectors Quest
      description: |
        CollectorsQuest.com gives you an exclusive look at the Pawn Stars Collectibles.
        See these and other TV Show Collectibles.

    americanPickers:
      title: American Pickers | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the American Pickers collection.
        CollectorsQuest.com gives you an inside look at the American Pickers collectibles.

    franksPicks:
      title: American Pickers: Frank's Picks | Collectors Quest
      description: |
        Enter the private collection of Frank Fritz, host of HISTORY's American Pickers!
        Shop from items seen on TV and Frank's personal picks, exclusively on Collectors Quest.
        Check back for new items being added often!

    americanRestoration:
      title: American Restoration | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the American Restoration collection.
        CollectorsQuest.com gives you an inside look at the American Restoration collectibles.

    pickedOff:
      title: Picked Off | TV Show Collectibles | Collectors Quest
      description: |
        Check out these collectors items from the Picked Off collection.
        CollectorsQuest.com gives you an inside look at the Picked Off collectibles.

    mwba:
      title: The Men Who Built America | Collectors Quest
      description: |
        Vanderbilt, Roosevelt & Rockefeller : The Men Who Built America

    mwbaPetroliana:
      title: John D. Rockefeller | Oil, Gas & Petroliana | Collectors Quest
      description: |
        Oil cans, gas pumps, station signs and other petroliana have all found their way
        into the hands of dedicated collectors, and all come from the outstanding legacy of
        John D. Rockefeller.

    mwbaRooseveltiana:
      title: Theodore Roosevelt | Politics & Rooseveltiana | Collectors Quest
      description: |
        Rooseveltiana collectors have collected their share of political buttons,
        but one can also find his face and figure on clocks and watches, knives, banks,
        plates, and many other collectibles.

    mwbaRailroadiana:
      title: Cornelius Vanderbilt | Trains & Railroadiana | Collectors Quest
      description: |
        Railroadiana aficionados owe Vanderbilt a great debt as they collect and display
        railroad signs, lanterns, scale models, and even conductors’ caps that celebrate his legacy.

  categories:
    index:
      title: Browse Antique, Collectible & Vintage Items | Collectors Quest
      description: |
        Browse collectible, vintage & antique items on display at Collectors Quest.
        Share, interact, and show off your own collections!

    category:
      model: true
      title: %SeoCollectionsTitle%
      description:
        - |
          Browse collectible, vintage and antique items on Collectors Quest,
          like these %Name% items, posted by trusted sellers and passionate collectors!
        - %SeoCollectionsDescription%

  collections:
    title: Unique Antique, Collectible & Vintage Items | Collectors Quest
    description: |
      Browse our amazing collections of antique, vintage & collectible items
      from passionate collectors around the world.

  # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11746674-collection-page
  collection:
    index:
      model: true
      title:
        - %Name%
        - %Name% | Collectors Quest
        - %Name% by %Collector%
        - %Name% by %Collector% | Collectors Quest
        - %Name% - %TagString% | Collectors Quest
        - %Name% by %Collector% - %TagString%
        - %Name% by %Collector% - %TagString% | Collectors Quest
      description:
        - %Description%
        - %Description% | %TagString%
        - %Description% | From %ContentCategory% | %TagString%

    # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11739468-collectible-product
    collectible:
      model: true
      title:
        - %Name%
        - %Name% | Collectors Quest
        - %Name% by %Collector% | Collectors Quest
        - %Name% - %Collection% | Collectors Quest
        - %Name% - %Collection% by %Collector%
        - %Name% - %Collection% by %Collector% | Collectors Quest
      description:
        - %Description%
        - %Description% | %Name%
        - %Description% | %Name% from %Collection%
        - %Description% | %Name% from %Collection% by %Collector%
        - %Description% | %Name% from %Collection% by %Collector% | %TagString%


  # https://basecamp.com/1759305/projects/288122-collectorsquest-com/todos/11749079-collector-page
  collector:
    index:
      model: true
      title:
        - %DisplayName% | Collectors Quest
        - %DisplayName%’s Collectibles | Collectors Quest
        - %DisplayName%’s Collectibles | Buy & Sell on Collectors Quest

    signup:
      title: Buy and Sell Collectibles Online | Sign Up at CollectorsQuest.com
      description: |
        Sign up to sell or buy collectibles online.
        CollectorsQuest.com provides a unique marketplace for buying and selling collectibles online.

  collectors:
    index:
      title: Newest Collectors & Sellers | Collectors Quest
      description: |
        Check out the newest members on Collectors Quest! Show off your antique,
        collectible and vintage items, meet other collectors and buy, sell or trade with others.

  marketplace:
    index:
      title: Buy & Sell Antiques, Collectibles & Vintage Items | Collectors Quest
      description: |
        Browse our amazing collections of antique, vintage & collectible items
        from passionate collectors around the world.

    holiday:
      title: Buy & Sell Antiques, Collectibles & Vintage Items | Collectors Quest
      description: |
        Browse our amazing collections of antique, vintage & collectible items
        from passionate collectors around the world.

    browse:
      model: true
      title:
        - %Name% | Collectors Quest
        - Buy %Name% on Collectors Quest
        - %SeoMarketTitle%
      description:
        - Buy, sell & trade on Collectors Quest! Find %Name% posted by passionate collectors and trusted sellers.
        - |
          Buy and sell antique, collectible & vintage items on Collectors Quest!
          Find %Name% posted by passionate collectors and trusted sellers.
        - %SeoMarketDescription%

    categories:
      title: Buy Antique Collectible & Vintage Marketplace Items | Collectors Quest
      description: |
        Find the collectible, vintage or antique item you’ve been looking for from trusted
        sellers in the Collectors Quest marketplace.

  seller:
    store:
      model: true
      title:
        - %StoreTitle%
        - %StoreTitle% | Collectors Quest
        - %StoreTitle% by %DisplayName% | Collectors Quest
      description:
        - %StoreDescription%

    signup:
      title: Sell on Collectors Quest | Which package is right for you?
      description: |
        Broader Exposure, Flat Rate with No Transaction Fees, List for Six Months!
        Sign up now!

  misc:
    guideToCollecting:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.

    guideDownload:
      title: The Essential Guide to Collecting - Free Download | Collectors Quest
      description: |
        Our Essential Guide to Collecting has tips for everyone, whether you're a new collector or
        an experienced hunter looking for the next item for your collection.

  search:
    index:
      title: Search for Collectibles, Collections, Blog Posts, Videos and more!
