default:
  enabled: true
  with_layout: false
  lifetime: 3600

_widgetFacebookRecommendations:
  lifetime: 604800

_widgetFacebookLikeBox:
  lifetime: 604800

# We cannot cache the widget because of the message form and the _csrf_token
_widgetCollector:
  enabled: false
