generator:
  class: IcePropelGenerator
  param:
    model_class:           Organization
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              Organization
    plural:                Organizations
    route_prefix:          organization
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        founder_id: { label: "Founder Collector" }
      list:    ~
      filter:
        class:  BackendOrganizationFormFilter
        display: [type, founder_id, access, name, url, phone]
      form:
        class:  BackendOrganizationForm
      edit:    ~
      new:     ~
