generator:
  class: IcePropelGenerator
  param:
    model_class:           CollectorCollection
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              CollectorCollection
    plural:                CollectorCollections
    route_prefix:          collection
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~

      fields:
        id: { label: ID }
        list_collector: { label: Collector }
        list_name: { label: Name }
        content_category_id: { label: Category }
        content_category: { label: Category }
        tag_string: { label: Tags }
        count_collectibles: { label: Collectibles }
        created_at: { label: Date, date_format: 'MM/dd/yyyy' }

      list:
        title: Collections
        display: [id, content_category, _list_collector, _list_name, tag_string, count_collectibles, created_at]
        sort: [created_at, desc]
        batch_actions: {}
        object_actions:
          _edit: ~
          _delete: ~
          encourageSeller: { label: 'Send a "become seller" email' }
        actions:
          export: { label: "Export to CSV", action: export, sf_format: csv }

      filter:
        fields:
          id: { label: 'Collection #' }
          created_at: { label: 'Date' }
        display: [id, name, created_at, content_category_id, secret_sale]
        class: BackendCollectorCollectionFormFilter

      export:
        sort: [id, asc]
        fields:
          category_path: { label: Category }
          count_collectibles: { label: Collectibles }
          list_url: { label: Link }
        display:
          - id
          - category_path
          - collector
          - name
          - _description
          - tag_string
          - count_collectibles
          - created_at
          - _list_url

      form:
        display: [content_category_id, name, description, tags]

      edit:
        title: Edit collection %%name%%
      new: ~
