generator:
  class: IcePropelGenerator
  param:
    model_class:           CollectorCollection
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              CollectorCollection
    plural:                CollectorCollections
    route_prefix:          collection
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~

      fields:
        id: { label: ID }
        collection_category_id: { label: Category }
        collection_category: { label: Category }
        tag_string: { label: Tags }
        count_collectibles: { label: Collectibles }
        created_at: { label: Date, date_format: 'MM/dd/yyyy' }

      list:
        title: Collections
        display: [id, collection_category, collector, =name, tag_string, count_collectibles, score, created_at]
        sort: [created_at, desc]
        batch_actions: {}
        actions:
          export: { label: "Export to CSV", action: export }

      filter:
        fields:
          id: { label: 'Collection #' }
          created_at: { label: 'Date' }
        display: [id, name, collection_category_id, created_at]
        class: BackendCollectorCollectionFormFilter

      export:
        sort: [id, asc]
        fields:
          count_collectibles: { label: Collectibles }
        display: [id, collection_category_parent, collection_category, collector, name, count_collectibles, created_at]

      form:
        display: [name, description, tags, collection_category_id, content_category_id]

      edit:
        title: Edit collection %%name%%
      new:     ~
