editSuccess:
  stylesheets:
    - /css/frontend/jquery/tagedit.css

  javascripts:
    - jquery/autogrow-input.js
    - jquery/tagedit.js

    - /assets/js/wysihtml5.js
    - /assets/js/bootstrap/wysihtml5.js
