
### A&E

aetn_landing:
  url: /history
  param: { module: aetn, action: landing }
  requirements: { sf_method: [GET] }

aetn_american_pickers:
  url: /history/american-pickers
  param: { module: aetn, action: americanPickers }
  requirements: { sf_method: [GET] }

aetn_american_restoration:
  url: /history/american-restoration
  param: { module: aetn, action: americanRestoration }
  requirements: { sf_method: [GET] }

aetn_franks_picks:
  url: /history/franks-picks
  param: { module: aetn, action: franksPicks }
  requirements: { sf_method: [GET] }

aetn_franks_picks_alternative:
  url: /franks-picks
  param: { module: aetn, action: franksPicks }
  requirements: { sf_method: [GET] }

aetn_pawn_stars:
  url: /history/pawn-stars
  param: { module: aetn, action: pawnStars }
  requirements: { sf_method: [GET] }

aetn_picked_off:
  url: /history/picked-off
  param: { module: aetn, action: pickedOff }
  requirements: { sf_method: [GET] }

aetn_storage_wars:
  url: /history/storage-wars
  param: { module: aetn, action: storageWars }
  requirements: { sf_method: [GET] }

aetn_mwba:
  url: /history/the-men-who-built-america
  param: { module: aetn, action: mwba }
  requirements: { sf_method: [GET] }

aetn_mwba_petroliana:
  url: /history/mwba/john-d-rockefeller-petroliana
  param: { module: aetn, action: mwbaPetroliana }
  requirements: { sf_method: [GET] }

aetn_mwba_rooseveltiana:
  url: /history/mwba/theodore-roosevelt-rooseveltiana
  param: { module: aetn, action: mwbaRooseveltiana }
  requirements: { sf_method: [GET] }

aetn_mwba_railroadiana:
  url: /history/mwba/cornelius-vanderbilt-railroadiana
  param: { module: aetn, action: mwbaRailroadiana }
  requirements: { sf_method: [GET] }

aetn_collectible_by_slug:
  url:  /aetn/collectible/:id/:slug
  class: cqPropelRoute
  options: { model: Collectible, type: object, method: getObjectForRoute }
  param: { module: collection, action: collectible }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }
