
### LEGACY

legacy_community_help:
  url:  /community/help
  param: { module: _legacy, action: help }

legacy_community:
  url:   /community
  param: { module: _legacy, action: redirectToCollections }

legacy_collectible_sell:
  url:  /collectible/sell
  param: { module: _legacy, action: redirectToCollections }

legacy_featured_week:
  url:   /community/spotlight/:id/:slug
  class: sfPropelRoute
  options: { model: Featured, type: object, method: getObjectForFeaturedWeek }
  param: { module: _legacy, action: redirectToCollections }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }

legacy_community_pages:
  url:  /community/:string
  param: { module: _legacy, action: redirectToCollections }
  requirements: { string: "[^/]+" }

legacy_seller_subscribe:
  url:   /seller/subscribe
  param: { module: _legacy, action: comingSoon }

legacy_collector_signup_facebook:
  url:   /collector/signup/facebook
  param: { module: collector, action: signup }

legacy_collections_most_recent:
  url:  /collections/filter/most-recent
  param: { module: _legacy, action: redirectToCollections }

legacy_collector_by_slug:
  url:  /collector/:slug
  class: sfPropelRoute
  options: { model: Collector, type: object, method: getObjectForRoute }
  param: { module: collector, action: index }
  requirements: { slug: '[\-\w\.]+' }

legacy_collectible_by_slug:
  url:  /collection/item/:id/:slug
  class: cqPropelRoute
  options: { model: Collectible, type: object, method: getObjectForRoute, statsd: true }
  param: { module: collection, action: collectible }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }

legacy_marketplace_category_by_slug:
  url:   /marketplace/category/:id/:slug
  param: { module: _legacy, action: redirectToMarketplaceCategory }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }

legacy_featured_week_page:
  url:  /featured-week/:slug
  param: { module: _legacy, action: redirectToCollections }

legacy_calendar_events:
  url:  /calendar/events/:string
  param: { module: _legacy, action: redirectToCollections }
  requirements: { string: "[^/]+" }

legacy_general_pages:
  url:  /general/:string
  param: { module: _legacy, action: redirectToCollections }
  requirements: { string: "[^/]+" }

legacy_redirect_pages:
  url:  /redirect/:string
  param: { module: _legacy, action: redirectToContentCategories }
  requirements: { string: "[^/]+" }

legacy_feed_pages:
  url:  /feed/:string
  param: { module: _legacy, action: redirectToContentCategories }
  requirements: { string: "[^/]+" }

legacy_collectibles_for_sale_by_collector:
  url:  /collectibles-for-sale/by/:id/:store_slug
  class: cqPropelRoute
  options: { model: Collector, type: object, method: getObjectForRoute }
  param: { module: _legacy, action: redirectToSellerStore }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }
