## ORGANIZATIONS

organization_join:
  url:  /organization/:id/join
  class:  cqPropelORMRoute
  options:
    model:  Organization
    type:   object
    statsd: false
    column: id
  param: { module: organization, action: join }
  requirements: { id: '\d+', sf_method: 'post' }

organization_by_slug:
  url:    /organization/:id/:slug
  class:  cqPropelORMRoute
  options:
    model:  Organization
    type:   object
    statsd: true
    column: id
  param:  { module: organization, action: index }
  requirements: { id: '\d+', slug: '[\-\w\.]+' }

