all:
  response:
    class: cqWebResponse

  routing:
    class: cqPatternRouting
    param:
      generate_shortest_url: true
      extra_parameters_as_query_string: true

  user:
    class: cqUser
    param:
      timeout:         86400
      logging:         %SF_LOGGING_ENABLED%
      use_flash:       true
      default_culture: %SF_DEFAULT_CULTURE%

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true

  storage:
    class: cqSessionStorage
    param:
      session_name: legacy

  mailer:
    class: cqMailer
    param:
      logging: %SF_LOGGING_ENABLED%
      charset: %SF_CHARSET%
      delivery_strategy: realtime
      transport:
        class: Swift_AWSTransport

prod:
  logger:
    class:   sfNoLogger
    param:
      level:   err
      loggers: ~

  view_cache:
    class: sfMemcacheCache
    param:
      host: memcached
      port: 11211
      persistent: true

dev:
  mailer:
    class: cqMailer
    param:
      delivery_strategy: single_address
      delivery_address:  developers@collectorsquest.com
      transport:
        class: Swift_SmtpTransport
        param:
          host: localhost
          port: 25

  view_cache:
    class: sfMemcacheCache
    param:
      host: 127.0.0.1
      port: 11211
      persistent: true

cli:
  controller:
    class: sfConsoleController
  request:
    class: sfConsoleRequest
  response:
    class: sfConsoleResponse

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  request:
    class: cqWebTestRequest

  response:
    class: cqWebTestResponse
    param:
      send_http_headers: false

  mailer:
    class: sfMailer
    param:
      delivery_strategy: none
