rendering: ~
remember_me:
  class: cqCollectorRememberMeFilter
security:  ~

cqCompleteRegistration:
  class: cqCompleteRegistrationFilter

IceRequestHistory:
  class: IceRequestHistoryFilter

cache:     ~
execution: ~
