generator:
  class: IcePropelGenerator
  param:
    model_class:           ShoppingCartCollectible
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ShoppingCartCollectible
    plural:                ShoppingCartCollectibles
    route_prefix:          shopping_cart_collectible
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        list_collector: { label: Buyer }
        list_collectible: { label: Collectible }
        list_price: { label: Price }
        list_shipping: { label: Shipping Rate }
        created_at: { label: Date, date_format: 'MM/dd/yyyy' }
      list:
        title: Shopping Cart
        display: [_list_collector, _list_collectible, _list_price, _list_shipping, created_at]
        sort: [created_at, desc]
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        display: [created_at]
      form:    ~
      edit:    ~
      new:     ~
      export:  ~
