generator:
  class: IcePropelGenerator
  param:
    model_class:           ShoppingCartCollectible
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ShoppingCartCollectible
    plural:                ShoppingCartCollectibles
    route_prefix:          shopping_cart_collectible
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        shopping_cart_id: { label: Cart }
        shipping_country_iso3166: { label: Shipping Country }
        shipping: { label: Shipping Rate }
        price_amount: { label: Price }
        price_currency: { label: Currency }
      list:
        display: [shopping_cart_id, collectible, _price, shipping_country_iso3166, _shipping, is_active]
        actions: {}
        object_actions: {}
        batch_actions: {}
      filter:
        display: [collectible_id, price_amount, shipping_country_iso3166, shipping_type, is_active]
      form:    ~
      edit:    ~
      new:     ~
      export:  ~
