generator:
  class: IcePropelGenerator
  param:
    model_class:           ShoppingCartCollectible
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              ShoppingCartCollectible
    plural:                ShoppingCartCollectibles
    route_prefix:          shopping_cart_collectible
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [shopping_cart_id, collectible_id, price_amount, price_currency, shipping_country_iso3166, shipping_type, is_active]
      filter:
        display: [collectible_id, price_amount, shipping_country_iso3166, shipping_type, is_active]
      form:    ~
      edit:    ~
      new:     ~
      export:  ~
