all:
  stylesheets: [frontend/modules/blog.css]
  components:
    # breadcrumbs: [_blog, breadcrumbs]
    sidebar_300: [_blog, sidebar]

indexSuccess:
  metas:
    title: ~
    description: ~
    keywords: ~
