all:
  ice_libs:
    emails:
      sender: "no-reply@collectorsquest.com"
      notify: "developers@collectorsquest.com"

  ice_backend:
    god_auth:
      secret: "s6nr1ea16fo1br0wn5a31wnzhhazerr8"
      timeout:  3600

  ice_assets:
    domain: "d2y8496azcwpd6.cloudfront.net"

  ice_multimedia:
    default_adapter: ImageMagick

  aetn:
    shows:
      american_pickers:
        name: American Pickers®
        collector: 6668
        collection: 2842
        franks_picks: 4224
      american_restoration:
        name: American Restoration™
        collector: 14728
        collection: 3961
      pawn_stars:
        name: Pawn Stars®
        collector: 6667
        collection: 2841
      picked_off:
        name: Picked Off™
        collector: 13389
        collection: 3751
      mwba:
        name: The Men Who Built America
        collector: -1
        collection: -1
      storage_wars:
        name: Storage Wars™
        collector: -1
        collection: -1
      franks_picks:
        name: Frank's Picks
        collection: 4224
        collectibles: [97093, 97001, 96979, 96820, 96783, 96689, 96747, 96916, 97007, 97027, 96738, 97053, 96760, 96733, 96798]

    # Leave this for now for BC
    american_pickers:
      collector: 6668
      collection: 2842
      franks_picks: 4224
    american_restoration:
      collector: 14728
      collection: 3961
    pawn_stars:
      collector: 6667
      collection: 2841
    picked_off:
      collector: 13389
      collection: 3751


  credentials:
    akismet: "8fd3f2fddbaa"
    google_maps: "ABQIAAAAFWhrOd_LZ8oN4w-vkUWughQAU-WnqYQCO7zppSGvHR51tCrN4xRY0TaQWDhMG_uhoslQtMZplJu3gg"
    disqus_user_key: "rCJyPA1GJlX3hoF3tdSdrGbbeGBeI7I9G1Qspd5QuR6AiCscBxREmoo1SLBnlJyf"
    disqus_forum_key: "nqopSzGkkro8tc53AgA3DNW56WSYBbZRetdoNPE8whwKY7b7dvELc05Nm9Yq5nMD"
    impermium: "6eed575e07cc2431293287a570d0afd0c3efde87"
    defensio: "bb85a65a8118c50aa3918cb254a34176"
    dlvrit: "123456789abcdefg"
    mailchimp: "42b5522d9b347e1fe999d5dd8825ca53-us5"

    aws:
      key: "abcdef123456789"
      secret_key: "123456789abcdef"

    aviary:
      api_key: "3058e289b"
      api_secret: "694b2d643"
      hmac_secret: "o67NpB1P2xKJdV2J5KtUvLP9myVMIIG2sPr2xVHJ3JBQXo6njy1H5udSHobAL4vz"

    recaptcha:
      public_key: "6LdACwsAAAAAAE5tZTcYG47Lth2jzxxZeXAbll-Z"
      private_key: "6LdACwsAAAAAAM19l6G0lFk4F560SWvBM2k5M9L0"

    facebook:
      application_id: "293221397397430"
      application_secret: "21b6fb4368bbe3bf4157afe83e6945d4"
      admins: "119338990397,74502459,555733876,501327639"

  paypal:
    sandbox: true
    application_id: "APP-80W284485P519543T"
    api_username: "kangov_1327417143_biz_api1.collectorsquest.com"
    api_password: "1327417177"
    api_signature: "A..-CRlw0YpkY2B3ut0vv.OPym-eAT-VZrXVgkU8OKXkg-3ddWsYS50Q"

    merchant_account: "kangov_1327417143_biz@collectorsquest.com"
    url: "https://www.sandbox.paypal.com/cgi-bin/webscr"

  magnify:
    channel: video.collectorsquest.com
    api_key: K3VQWW33PCMK50HY
    sso_secret_key: ifHiFRaGaMH87b


  rocketshipit:
    generic:
      # 1 for Debug mode; 0 for normal operations
      # This also changes from testing to production mode
      debugMode: 1

      # Your company name
      shipper: ''

      # Key shipping contact individual at your company
      shipContact: ""

      shipAddr1: ''
      shipAddr2: ''
      shipCity: ''

      # the two-letter State or Province code
      # ex. MT: Montana, ON = Ontario
      shipState: ''

      # The Zip or Postal code
      shipCode: ''

      # The two-letter country code
      shipCountry: ''

      # Phone number in this format: 1234567890
      shipPhone: '1231231234'
      toCountry: 'US'


    fedex:
      # Your FedEx developer key
      key: ''

      # Your FedEx developer password
      password: ''

      # Your FedEx accountNumber
      accountNumber: ''

      # Your FedEx meter number
      meterNumber: ''

      # Allowed packaging types:
      # FEDEX_10KG_BOX
      # FEDEX_25KG_BOX
      # FEDEX_BOX
      # FEDEX_ENVELOPE
      # FEDEX_PAK
      # FEDEX_TUBE
      # YOUR_PACKAGING
      packagingType: ''

      # The two possible weight units are LB and KG
      weightUnit: ''

      # The two possible length units are IN and CM
      lengthUnit: ''

      # EUROPE_FIRST_INTERNATIONAL_PRIORITY
      # FEDEX_1_DAY_FREIGHT
      # FEDEX_2_DAY
      # FEDEX_2_DAY_FREIGHT
      # FEDEX_3_DAY_FREIGHT
      # FEDEX_EXPRESS_SAVER
      # FEDEX_GROUND
      # FIRST_OVERNIGHT
      # GROUND_HOME_DELIVERY
      # INTERNATIONAL_ECONOMY
      # INTERNATIONAL_ECONOMY_FREIGHT
      # INTERNATIONAL_FIRST
      # INTERNATIONAL_PRIORITY
      # INTERNATIONAL_PRIORITY_FREIGHT
      # PRIORITY_OVERNIGHT
      # SMART_POST
      # STANDARD_OVERNIGHT
      # FEDEX_FREIGHT
      # FEDEX_NATIONAL_FREIGHT
      service: ''

      # REGULAR_PICKUP
      # REQUEST_COURIER
      # DROP_BOX
      # BUSINESS_SERVICE_CENTER
      # STATION
      dropoffType: ''

      # COLLECT
      # RECIPIENT
      # SENDER
      # THIRD_PARTY
      paymentType: ''

      # COMMON2D
      # LABEL_DATA_ONLY
      labelFormatType: ''

      # DPL
      # EPL2
      # PDF
      # PNG
      # ZPLII
      imageType: ''

      # PAPER_4X6
      # PAPER_4X8
      # PAPER_4X9
      # PAPER_7X4.75
      # PAPER_8.5X11_BOTTOM_HALF_LABEL
      # PAPER_8.5X11_TOP_HALF_LABEL
      # STOCK_4X6
      # STOCK_4X6.75_LEADING_DOC_TAB
      # STOCK_4X6.75_TRAILING_DOC_TAB
      # STOCK_4X8
      # STOCK_4X9_LEADING_DOC_TAB
      # STOCK_4X9_TRAILING_DOC_TAB
      labelStockType: ''

      # BILL_OF_LADING
      # COD_RETURN_TRACKING_NUMBER
      # CUSTOMER_AUTHORIZATION_NUMBER
      # CUSTOMER_REFERENCE
      # DEPARTMENT
      # FREE_FORM_REFERENCE
      # GROUND_SHIPMENT_ID
      # GROUND_MPS
      # INVOICE
      # PARTNER_CARRIER_NUMBER
      # PART_NUMBER
      # PURCHASE_ORDER
      # RETURN_MATERIALS_AUTHORIZATION
      # TRACKING_CONTROL_NUMBER
      # TRACKING_NUMBER_OR_DOORTAG
      # SHIPPER_REFERENCE
      # STANDARD_MPS
      trackingIdType: ''

    ups:
      # Your UPS Developer license
      # your UPS XML Access Key, we need to insert link to get one
      license: ''

      # your UPS Developer username
      username: ''

      # your ups Developer password
      password: ''

      # Make sure addresses are valid before label creation
      # validate, nonvalidate
      verifyAddress: 'nonvalidate'

      # The following variables govern the way the system functions
      # Options
      # ZPL - Zebra UPS Thermal Printers
      # EPL - Eltron UPS Thermal Printers
      # GIF - Image based, desktop inkjet printers
      # STARPL
      # SPL
      labelPrintMethodCode: ''

      # Used when printing GIF images
      httpUserAgent: ''

      # Only valid option for ZPL, EPL, STARPL, and SPL is 4
      # When using inches use whole numbers only
      labelHeight: ''

      # Options are 6 or 8 inches
      labelWidth: ''

      # Options
      # GIF - A gif image
      labelImageFormat: ''

      # The following variables are for your UPS account
      # They typically don't change from shipment to shipment although,
      # you may set any of them directly.
      # Your UPS Account number
      accountNumber: ''

      # Options
      # 01 - Daily Pickup
      # 03 - Customer Counter
      # 06 - One Time Pickup
      # 07 - On Call Air
      # 11 - Suggested Retail Rates
      # 19 - Letter Center
      # 20 - Air Service Center
      PickupType: ''

      # LBS or KGS
      weightUnit: ''

      # IN, or CM
      lengthUnit: ''

      # See the ups manual for a list of all currency types
      insuredCurrency: 'USD'

      # two-letter country code
      toCountryCode: 'US'

      # The following variables set the defaults for individual shipments
      # you may set them here to save time, or you may set them explicitly
      # each time you use the classes.
      shipmentDescription: 'My RocketShipIt Shipment'

      # Options
      # 01 - UPS Next Day Air
      # 02 - UPS Second Day Air
      # 03 - UPS Ground
      # 07 - UPS Worldwide Express
      # 08 - UPS Worldwide Expedited
      # 11 - UPS Standard
      # 12 - UPS Three-Day Select
      # 13 - Next Day Air Saver
      # 14 - UPS Next Day Air Early AM
      # 54 - UPS Worldwide Express Plus
      # 59 - UPS Second Day Air AM
      # 65 - UPS Saver
      service: ''

      # Options
      # 01 - UPS Letter
      # 02 - Your Packaging
      # 03 - Tube
      # 04 - PAK
      # 21 - Express Box
      # 24 - 25KG Box
      # 25 - 10KG Box
      # 30 - Pallet
      # 2a - Small Express Box
      # 2b - Medium Express Box
      # 2c - Large Express Box
      packagingType: ''

      packageDescription: ''

      # Set '0' for commercial '1' for residential
      residentialAddressIndicator: '0'

      # Set '0' for retail rates '1' for negotiated
      # You must turn this on with your UPS account rep
      negotiatedRates: '0'

      # Options
      # AJ Accounts Receivable Customer Account
      # AT Appropriation Number
      # BM Bill of Lading Number
      # 9V Collect on Delivery (COD) Number
      # ON Dealer Order Number
      # DP Department Number
      # 3Q Food and Drug Administration (FDA) Product Code
      # IK Invoice Number
      # MK Manifest Key Number
      # MJ Model Number
      # PM Part Number
      # PC Production Code
      # PO Purchase Order Number
      # RQ Purchase Request Number
      # RZ Return Authorization Number
      # SA Salesperson Number
      # SE Serial Number
      # ST Store Number
      # TN Transaction Reference Number
      referenceCode: '02'

      # Options
      # 2 - UPS Print and Mail (PNM)
      # 3 - UPS Return Service 1-Attempt (RS1)
      # 5 - UPS Return Service 3-Attempt (RS3)
      # 8 - UPS Electronic Return Label (ERL)
      # 9 - UPS Print Return Label (PRL)
      returnCode: ''


    usps:
      # USPS userID
      # Please note: the USPS test servers only respond to pre-defined requests.
      # For USPS rates you need to call USPS and have them move you to
      # the production servers.
      userid: ''

      # USPS service type
      # FIRST CLASS
      # PRIORITY
      # PRIORITY COMMERCIAL
      # EXPRESS
      # EXPRESS COMMERCIAL
      # EXPRESS SH
      # EXPRESS SH COMMERCIAL
      # EXPRESS HFP
      # EXPRESS HFP
      # COMMERCIAL
      # BPM
      # PARCEL
      # MEDIA
      # LIBRARY
      # ALL
      # ONLINE
      service: ''

      # Values:
      # REGULAR
      # LARGE (Length + girth over 84in under 109in)
      # OVERSIZE (length + girth over 108 under 131)
      size: ''

      # FLAT
      firstClassMailType: ''

dev:
  domain_name: "collectorsquest.dev"
  www_domain: "www.collectorsquest.dev"
  static_domain: "www.collectorsquest.dev"
  multimedia_domain: "multimedia.cqcdns.dev"

  ice_libs:
    kint:
      enabled: true
      path_display_callback: 'Kint::_kintLine'

  ice_assets:
    domain: "cqcdns.dev"

  paypal:
    ipn_domain: 'http://manhattan.dyndns-office.com'

test:
  domain_name: "example.com"
  www_domain: "www.example.com"
  static_domain: "static.example.com"
  multimedia_domain: "multimedia.example.com"
