connection:  propel
noXsd:  false
defaultIdMethod:  native
package:  lib.model.plugins.iceGeoLocationPlugin
encoding:  utf8

classes:
  GeoCountry:
    tableName: geo_country
    phpName: iceModelGeoCountry
    columns:
      id:  ~
    uniques:
      geo_country_U_2: [iso3166]
    behaviors:
      PropelActAsSluggableBehavior:
        columns: { from: geo_country.name, to: geo_country.slug }
        separator: "-"
        permament: false
        lowercase: false

  GeoRegion:
    tableName: geo_region
    phpName: iceModelGeoRegion
    columns:
      id:  ~
      geo_country_id:  { type: integer, required: true, foreignClass: GeoCountry, foreignReference: id, onDelete: cascade }

  GeoCity:
    tableName: geo_city
    phpName: iceModelGeoCity
    columns:
      id:  ~
      geo_region_id:  { type: integer, required: true, foreignClass: GeoRegion, foreignReference: id, onDelete: cascade }

  GeoArea:
    tableName: geo_area
    phpName: iceModelGeoArea
    columns:
      id:  ~
      geo_region_id:  { type: integer, required: true, foreignClass: GeoRegion, foreignReference: id, onDelete: cascade }
      geo_city_id:    { type: integer, required: true, foreignClass: GeoCity, foreignReference: id, onDelete: cascade }

  GeoStreet:
    tableName: geo_street
    phpName: iceModelGeoStreet
    columns:
      id:  ~
      geo_region_id:  { type: integer, required: true, foreignClass: GeoRegion, foreignReference: id, onDelete: cascade }
      geo_city_id:    { type: integer, required: true, foreignClass: GeoCity, foreignReference: id, onDelete: cascade }
      geo_area_id:    { type: integer, required: true, foreignClass: GeoArea, foreignReference: id, onDelete: cascade }
