connection: archive
noXsd: false
defaultIdMethod: native
package: lib.model.archive

classes:
  CollectorArchive:
    columns:
      id:             { type: integer, primaryKey: true, autoIncrement: false }
      graph_id:       { type: integer, required: false, index: true }
      facebook_id:    { type: varchar, size: 20, index: true }
      username:       { type: varchar, size: 64, required: true }
      display_name:   { type: varchar, size: 64, required: true, primaryString: true }
      slug:           { type: varchar, size: 64, required: true, index: true }
      sha1_password:  { type: varchar, size: 40, required: true }
      portable_password:  { type: varchar, size: 64, required: true }
      salt:           { type: varchar, size: 32, required: true }
      email:          { type: varchar, size: 128, index: true }
      user_type:      { type: char, sqlType: "ENUM('Collector','Seller')", default: "Collector", required: true }
      locale:         { type: varchar, size: 5, default: "en_US" }
      score:          { type: integer, default: 0 }
      average_rating:         { type: float, default: 0 }
      average_content_rating: { type: float, default: 0 }
      average_images_rating:  { type: float, default: 0 }
      spam_score:     { type: integer, default: 0 }
      is_spam:        { type: boolean, default: false }
      is_public:      { type: boolean, default: true }
      has_completed_registration: { type: boolean, default: false }
      session_id:     { type: varchar, size: 32 }
      cookie_uuid:    { type: varchar, size: 32 }
      last_seen_at:   { type: timestamp }
      last_visited_at: { type: timestamp }

      eblob:        { type: longvarchar, default: null }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CollectorProfileArchive:
    columns:
      collector_id:    { type: integer, primaryKey: true}
      collector_type:  { type: enum, valueSet: "casual, occasional, serious, obsessive, expert", default: casual, required: true }
      birthday:        { type: date }
      gender:          { type: char, sqlType: "ENUM('f','m')" }
      zip_postal:      varchar(10)
      country_iso3166: varchar(2)
      website:         varchar(128)
      num_views:       { type: integer, default: 0 }
      is_featured:     { type: boolean, default: false }
      is_seller:       { type: boolean, default: false }
      is_image_auto:   { type: boolean, default: true }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CollectorIdentifierArchive:
    columns:
      id:            { type: integer, primaryKey: true, autoIncrement: false }
      collector_id:  { type: integer, index: true }
      identifier:    { type: varchar, size: 255, index: true }
      created_at:    { type: timestamp }
      archived_at:   { type: timestamp }

    propel_behaviors:
      symfony:       { form: false, filter: false }


  CollectorGeocacheArchive:
    columns:
      id:               { type: integer, primaryKey: true, autoIncrement: false }
      collector_id:     { type: integer, index: true }
      country_iso3166:  { type: char, size: 2 }
      state:            { type: varchar, size: 64 }
      county:           { type: varchar, size: 64 }
      city:             { type: varchar, size: 64 }
      zip_postal:       { type: char, size: 10 }
      address:          { type: varchar, size: 128 }
      latitude:         { type: float, sqlType: "DECIMAL(8,5)" }
      longitude:        { type: float, sqlType: "DECIMAL(8,5)" }
      timezone:         { type: varchar, size: 128 }

    propel_behaviors:
      symfony:          { form: false, filter: false }


  CollectionArchive:
    columns:
      id:                      { type: integer, primaryKey: true, autoIncrement: false }
      graph_id:                { type: integer, required: false, index: index }
      collection_category_id:  { type: integer, index: true }
      content_category_id:     { type: integer, index: true }
      descendant_class:        { type: varchar, size: 100 }
      name:                    { type: varchar, size: 255, required: true, primaryString: true }
      slug:                    { type: varchar, size: 128 }
      description:             { type: longvarchar, required: true }
      num_items:               { type: integer, default: 0 }
      num_public_items:        { type: integer, default: 0 }
      num_views:               { type: integer, default: 0 }
      num_comments:            { type: integer, default: 0 }
      num_ratings:             { type: integer, default: 0 }
      score:                   { type: integer, default: 0 }
      average_rating:          { type: float, default: 0 }
      average_content_rating:  { type: float, default: 0 }
      average_images_rating:   { type: float, default: 0 }
      is_public:               { type: boolean, default: true }
      is_featured:             { type: boolean, default: false }
      comments_on:             { type: boolean, default: true }
      rating_on:               { type: boolean, default: true }

      eblob:        { type: longvarchar, default: null }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  ContentCategoryArchive:
    columns:
      id:                      { type: integer, primaryKey: true, autoIncrement: false }
      collection_category_id: { type: integer, required: false, index: true }
      name:         { type: varchar, size: 64, required: true }
      slug:         { type: varchar, size: 64, required: true }
      description:  { type: longvarchar, required: false }
      tree_left:    { type: integer }
      tree_right:   { type: integer }
      tree_level:   { type: integer }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CollectorCollectionArchive:
    columns:
      id:                      { type: integer, primaryKey: true, autoIncrement: false }
      graph_id:                { type: integer, required: false, index: index }
      collector_id:            { type: integer, index: true }
      collection_category_id:  { type: integer, index: true }
      content_category_id:     { type: integer, index: true }
      name:                    { type: varchar, size: 255, required: true, primaryString: true }
      slug:                    { type: varchar, size: 128 }
      description:             { type: longvarchar, required: true }
      num_items:               { type: integer, default: 0 }
      num_public_items:        { type: integer, default: 0 }
      num_views:               { type: integer, default: 0 }
      num_comments:            { type: integer, default: 0 }
      num_ratings:             { type: integer, default: 0 }
      score:                   { type: integer, default: 0 }
      average_rating:          { type: float, default: 0 }
      average_content_rating:  { type: float, default: 0 }
      average_images_rating:   { type: float, default: 0 }
      is_public:               { type: boolean, default: true }
      is_featured:             { type: boolean, default: false }
      comments_on:             { type: boolean, default: true }
      rating_on:               { type: boolean, default: true }

      eblob:        { type: longvarchar, default: null }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CollectibleArchive:
    columns:
      id:                { type: integer, primaryKey: true, autoIncrement: false }
      graph_id:          { type: integer, required: false, index: index }
      collector_id:      { type: integer, index: true }
      content_category_id: { type: integer, required: false, index: true }
      name:              { type: varchar, size: 255, required: true, primaryString: true }
      slug:              { type: varchar, size: 128, index: true }
      description:       { type: longvarchar, required: true }
      batch_hash:        { type: varchar, size: 32, index: true }
      num_views:         { type: integer, default: 0 }
      num_comments:      { type: integer, default: 0 }
      score:             { type: integer, default: 0 }
      average_rating:         { type: float, default: 0 }
      average_content_rating: { type: float, default: 0 }
      average_images_rating:  { type: float, default: 0 }
      is_name_automatic: { type: boolean, default: false }
      is_public:         { type: boolean, default: true }

      eblob:        { type: longvarchar, default: null }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CollectibleForSaleArchive:
    columns:
      collectible_id:       { type: integer, index: true, primaryKey: true, autoIncrement: false }
      price_amount:         { type: integer, required: true, default: 0 }
      price_currency:       { type: char, size: 3, required: true, default: 'USD' }
      tax_country:          { type: char, size: 2, required: false }
      tax_state:            { type: varchar, size: 100, required: false }
      tax_percentage:       { type: integer, required: false }
      condition:            { type: char, sqlType: "ENUM('excellent','very good','good','fair','poor')", required: true }
      is_price_negotiable:  { type: boolean, default: false }
      is_ready:             { type: boolean, default: false, description: 'Show in the market or not' }
      marked_for_sale_at:   { type: timestamp }
      is_sold:              { type: boolean, default: false }
      quantity:             { type: integer, required: true, default: 1 }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  CommentArchive:
    columns:
      id:              { type: integer, primaryKey: true, autoIncrement: false }
      disqus_id:       { type: char, size: 10 }
      parent_id:       { type: char, size: 10 }
      collection_id:   { type: integer, index: true }
      collectible_id:  { type: integer, index: true }
      collector_id:    { type: integer, index: true }
      model:           { type: char, size: 64, required: true }
      model_id:        { type: integer, required: true }
      author_name:     { type: varchar, size: 128 }
      author_email:    { type: varchar, size: 128 }
      author_url:      { type: varchar, size: 255 }
      is_notify:       { type: boolean, required: true, default: false }
      is_hidden:       { type: boolean, required: true, default: false }
      is_spam:         { type: boolean, required: true, default: false }
      subject:         { type: varchar, size: 128 }
      body:            { type: longvarchar, required: true }
      ip_address:      { type: varchar, size: 15 }

      created_at:      { type: timestamp }
      archived_at:     { type: timestamp }

    propel_behaviors:
      symfony:         { form: false, filter: false }


  ShoppingOrderArchive:
    columns:
      id:                   { type: integer, primaryKey: true, autoIncrement: false }
      uuid:                 { type: varchar, size: 8 }
      seller_id:            { type: integer, index: true }
      collector_id:         { type: integer, index: true }
      shopping_cart_id:     { type: integer, index: true }
      collectible_id:       { type: integer, index: true }
      shopping_payment_id:  { type: integer, index: true }
      buyer_email:          { type: varchar, size: 128, index: true }

      shipping_address_id:       { type: integer, index: true }
      shipping_full_name:        { type: varchar(255), required: true  }
      shipping_phone:            { type: varchar(50),  required: false }
      shipping_address_line_1:   { type: varchar(255), required: true  }
      shipping_address_line_2:   { type: varchar(255), required: false }
      shipping_city:             { type: varchar(100), required: true  }
      shipping_state_region:     { type: varchar(100), required: false }
      shipping_zip_postcode:     { type: varchar(50),  required: true }
      shipping_country_iso3166:  { type: char, size: 2, required: false }

      shipping_carrier:          { type: enum, required: false, valueSet: "FedEx, UPS, USPS, DHL" }
      shipping_tracking_number:  { type: varchar(64), required: false }

      note_to_seller:       { type: varchar, size: 255 }
      progress:             { type: enum, valueSet: "step1, step2, step3", default: step1, required: true }

      is_buyer_notified:         { type: boolean, default: false }
      is_seller_notified:        { type: boolean, default: false }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }


  ShoppingPaymentArchive:
    columns:
      id:                   { type: integer, primaryKey: true, autoIncrement: false }
      shopping_order_id:   { type: integer, index: true }
      cookie_uuid:         { type: varchar, size: 32, required: false }
      processor:           { type: enum, valueSet: "PayPal, Google, Amazon", default: PayPal, required: true }
      status:              { type: enum, valueSet: "initialized, inprogress, confirmed, cancelled, failed, completed", default: initialized, required: true }
      currency:            { type: char, size: 3, default: USD }
      amount_total:        { type: integer, required: true, default: 0 }
      amount_collectibles: { type: integer, required: true, default: 0 }
      amount_shipping_fee: { type: integer, required: true, default: 0 }
      amount_tax:          { type: integer, required: true, default: 0 }
      seller_promotion_id: { type: integer, required: false, index: true }
      amount_promotion:    { type: integer, required: false, default: 0 }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }

  SellerPromotionArchive:
    columns:
      id:               { type: integer, primaryKey: true, autoIncrement: false }
      seller_id:        { type: integer, index: true }
      collector_id:     { type: integer, index: true }
      collectible_id:   { type: integer, index: true }
      promotion_code:   { type: varchar, size: 100, required: true, index: true }
      promotion_name:   { type: varchar, size: 255, required: true, primaryString: true }
      promotion_desc:   { type: longvarchar }
      amount:           { type: integer, required: false, default: 0  }
      amount_type:      { type: enum, valueSet: "Fixed, Percentage, Free Shipping", required: true }
      quantity:         { type: integer, default: 0  }
      expiry_date:      { type: timestamp }
      is_expired:       { type: boolean, default: false }

      updated_at:   { type: timestamp }
      created_at:   { type: timestamp }
      archived_at:  { type: timestamp }

    propel_behaviors:
      symfony:      { form: false, filter: false }

