connection: propel
noXsd: false
defaultIdMethod: native
package: lib.model

classes:

  ###
  # NOTE: Make SURE to update also CollectorArchive in archive.schema.yml
  ##
  Collector:
    columns:
      id:  ~
      graph_id:       { type: integer, required: false, index: unique }
      facebook_id:    { type: varchar, size: 20, index: unique }
      username:       { type: varchar, size: 64, required: true }
      display_name:   { type: varchar, size: 64, required: true, primaryString: true }
      slug:           { type: varchar, size: 64, required: true, index: unique }
      sha1_password:  { type: varchar, size: 40, required: true }
      salt:           { type: varchar, size: 32, required: true }
      email:          { type: varchar, size: 128, index: unique }
      user_type:      { type: char, sqlType: "ENUM('Collector','Seller')", default: "Collector", required: true }
      items_allowed:  { type: integer, default: 0 }
      locale:         { type: varchar, size: 5, default: "en_US" }
      score:          { type: integer, default: 0 }
      spam_score:     { type: integer, default: 0 }
      is_spam:        { type: boolean, default: false }
      is_public:      { type: boolean, default: true }
      has_completed_registration: { type: boolean, default: false }
      session_id:     { type: varchar, size: 32 }
      last_seen_at:   { type: timestamp }

      eblob: { type: longvarchar, default: null }

    propel_behaviors:
      archivable: { archive_class: CollectorArchive, archived_at_column: archived_at }
      extra_properties: ~
      timestampable:  ~

  ###
  # NOTE: Make SURE to update also CollectorProfileArchive in archive.schema.yml
  ##
  CollectorProfile:
    columns:
      collector_id:    { type: integer, primaryKey: true, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      collector_type:  { type: enum, valueSet: "casual, occasional, serious, obsessive, expert", default: casual, required: true }
      birthday:        { type: date }
      gender:          { type: char, sqlType: "ENUM('f','m')" }
      zip_postal:      varchar(10)
      country_iso3166: { type: char, size: 2, required: false, foreignTable: geo_country, foreignReference: iso3166 }
      website:         varchar(128)
      is_featured:     { type: boolean, default: false }
      is_seller:       { type: boolean, default: false }
      is_image_auto:   { type: boolean, default: true }
      preferences:     longvarchar
      notifications:   longvarchar

    propel_behaviors:
      archivable: { archive_class: CollectorProfileArchive, archived_at_column: archived_at }
      extra_properties: ~
      timestampable:  ~

  CollectorEmail:
    columns:
      id:  ~
      collector_id:  { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      email:         { type: varchar, size: 128, index: true }
      hash:          { type: varchar, size: 128, required: true }
      salt:          { type: varchar, size: 32, required: true }
      is_verified:   { type: boolean, default: false }

    uniques:
      unq_collector_email: [collector_id, email]

    propel_behaviors:
      symfony:        { form: false, filter: false }
      timestampable:  ~

  CollectorAddress:
    columns:
      id:               ~
      collector_id:     { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      full_name:        { type: varchar(255), required: true  }
      address_line_1:   { type: varchar(255), required: true  }
      address_line_2:   { type: varchar(255), required: false }
      city:             { type: varchar(100), required: true  }
      state_region:     { type: varchar(100), required: false }
      zip_postcode:     { type: varchar(50),  required: false }
      country_iso3166:  { type: char, size: 2, required: true, foreignTable: geo_country, foreignReference: iso3166 }
      phone:            { type: varchar(50),  required: true  }
      is_primary:       { type: boolean, required: true, default: false }

  ###
  # NOTE: Make SURE to update also CollectorIdentifierArchive in archive.schema.yml
  ##
  CollectorIdentifier:
    columns:
      id:  ~
      collector_id:  { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      identifier:    { type: varchar, size: 255, index: unique }
      created_at:    ~

    propel_behaviors:
      archivable:    { archive_class: CollectorIdentifierArchive, archived_at_column: archived_at }
      symfony:       { form: false, filter: false }

  CollectorRememberKey:
    columns:
      id: ~
      collector_id:  { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      remember_key:  { type: char, size: 32 }
      ip_address:    { type: char, size: 15 }
      created_at:    ~

    propel_behaviors:
      symfony:       { form: false, filter: false }

  CollectorInterview:
    columns:
      id:  ~
      collector_id:            { type: integer, foreignClass: Collector, foreignReference: id, required: false, onDelete: setnull }
      collection_category_id:  { type: integer, foreignClass: CollectionCategory, foreignReference: id, onDelete: setnull }
      content_category_id:     { type: integer, foreignClass: ContentCategory, foreignReference: id, onDelete: setnull }
      collection_id:           { type: integer, foreignClass: Collection, foreignReference: id, onDelete: setnull }
      title:                   { type: varchar, size: 128, required: true, primaryString: true }
      catch_phrase:            { type: varchar, size: 128, required: true }
      is_active:               { type: boolean, default: false }
      created_at:  ~

  ###
  # NOTE: Make SURE to update also CollectorGeocacheArchive in archive.schema.yml
  ##
  CollectorGeocache:
    columns:
      id:  ~
      collector_id:     { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      country_iso3166:  { type: char, size: 2, required: false, foreignTable: geo_country, foreignReference: iso3166 }
      state:            { type: varchar, size: 64 }
      county:           { type: varchar, size: 64 }
      city:             { type: varchar, size: 64 }
      zip_postal:       { type: char, size: 10 }
      address:          { type: varchar, size: 128 }
      latitude:         { type: float, sqlType: "DECIMAL(8,5)" }
      longitude:        { type: float, sqlType: "DECIMAL(8,5)" }
      timezone:         { type: varchar, size: 128 }

    propel_behaviors:
      archivable:  { archive_class: CollectorGeocacheArchive, log_archived_at: false }
      symfony:     { form: false, filter: false }

  CollectorFriend:
    columns:
      id:  ~
      collector_id:  { type: integer, required: true, foreignClass: Collector, foreignReference: id }
      friend_id:     { type: integer, required: true, foreignClass: Collector, foreignReference: id }
      created_at:    ~

  InterviewQuestion:
    columns:
      id:  ~
      collector_interview_id:  { type: integer, foreignClass: CollectorInterview, foreignReference: id, required: true, onDelete: cascade }
      question:                { type: varchar, size: 128, required: true }
      answer:                  { type: longvarchar, required: true }
      photo:                   varchar(128)

  ###
  # NOTE: Make SURE to update also CollectionArchive in archive.schema.yml
  ##
  Collection:
    columns:
      id:  ~
      graph_id:                { type: integer, required: false, index: unique }
      collection_category_id:  { type: integer, foreignClass: CollectionCategory, foreignReference: id, onDelete: setnull }
      content_category_id:     { type: integer, foreignClass: ContentCategory, foreignReference: id, onDelete: setnull, required: false }
      name:                    { type: varchar, size: 255, required: true, primaryString: true }
      slug:                    { type: varchar, size: 128 }
      description:             { type: longvarchar, required: true }
      num_items:               { type: integer, default: 0 }
      num_views:               { type: integer, default: 0 }
      num_comments:            { type: integer, default: 0 }
      num_ratings:             { type: integer, default: 0 }
      score:                   { type: integer, default: 0 }
      is_public:               { type: boolean, default: true }
      is_featured:             { type: boolean, default: false }
      comments_on:             { type: boolean, default: true }
      rating_on:               { type: boolean, default: true }

      eblob: { type: longvarchar, default: null }

    propel_behaviors:
      sluggable: { slug_pattern: "{Name}", permanent: false }
      timestampable:  ~

  CollectionCategory:
    columns:
      id:  ~
      parent_id:  { type: integer, default: 0 }
      name:       { type: varchar, size: 64, required: true, primaryString: true }
      slug:       { type: varchar, size: 64 }
      score:      { type: integer, default: 0 }

  ContentCategory:
    columns:
      id: ~
      collection_category_id: { type: integer, required: false, foreignClass: CollectionCategory, foreignReference: id, onDelete: setnull }
      name:         { type: varchar, size: 64, required: true, primaryString: true }
      slug:         { type: varchar, size: 64, required: true }
      description:  { type: longvarchar, required: false }
    propel_behaviors:
      sluggable:  { slug_pattern: "{Name}", permanent: false }
      nested_set: ~

  CollectionCollectible:
    isCrossRef: true
    columns:
      collection_id:   { type: integer, required: true, foreignClass: Collection, foreignReference: id, onDelete: cascade, primaryKey: true }
      collectible_id:  { type: integer, required: true, foreignClass: Collectible, foreignReference: id, onDelete: cascade, primaryKey: true }
      score:           { type: integer, default: 0 }
      position:        { type: integer, default: 0 }
      is_primary:      { type: boolean, default: false }

    propel_behaviors:
      timestampable:  ~

  CollectorCollection:
    columns:
      collector_id:    { type: integer, required: true, foreignClass: Collector, foreignReference: id, onDelete: cascade }

    propel_behaviors:
      concrete_inheritance: { extends: collection, copy_data_to_parent: true }
      archivable: { archive_class: CollectorCollectionArchive, archived_at_column: archived_at }

  CollectionCategoryField:
    columns:
      id:  ~
      collection_category_id:  { type: integer, required: true, foreignClass: CollectionCategory, foreignReference: id, onDelete: cascade }
      custom_field_id:  ~
    uniques:
      collection_category_field: [collection_category_id, custom_field_id]

  ###
  # NOTE: Make SURE to update also CollectibleArchive in archive.schema.yml
  ##
  Collectible:
    columns:
      id:  ~
      graph_id:          { type: integer, required: false, index: unique }
      collector_id:      { type: integer, foreignClass: Collector, foreignReference: id, required: true, onDelete: cascade }
      name:              { type: varchar, size: 255, required: true, primaryString: true }
      slug:              { type: varchar, size: 128, index: unique }
      description:       { type: longvarchar, required: true }
      num_comments:      { type: integer, default: 0 }
      batch_hash:        { type: varchar, size: 32, index: true }
      score:             { type: integer, default: 0 }
      is_name_automatic: { type: boolean, default: false }

      eblob:             { type: longvarchar, default: null }

    propel_behaviors:
      archivable: { archive_class: CollectibleArchive, archived_at_column: archived_at }
      timestampable:  ~

  ###
  # NOTE: Make SURE to update also MultimediaArchive in archive.schema.yml
  ##
  Multimedia:
    columns:
      id:  ~
      model:        { type: char, size: 64, required: true }
      model_id:     { type: integer }
      type:         { type: char, sqlType: "ENUM('image','video')", default: image, required: true }
      name:         { type: varchar, size: 128 }
      md5:          { type: char, size: 32, required: true }
      colors:       { type: varchar(128) }
      orientation:  { type: char, sqlType: "ENUM('landscape','portrait')", default: landscape }
      source:       { type: varchar(255) }
      is_primary:   { type: boolean, default: false }

    indexes:
      multimedia_I_1: [model, model_id]

    uniques:
      multimedia_U_1: [model, model_id, md5]

    propel_behaviors:
      archivable: { archive_class: MultimediaArchive, archived_at_column: archived_at }
      timestampable:  ~

  PrivateMessage:
    columns:
      id:  ~
      thread:        { type: varchar, size: 32 }
      sender:        { type: integer, required: true, foreignClass: Collector, foreignReference: id, fkSkipSql: true }
      receiver:      { type: integer, required: true, foreignClass: Collector, foreignReference: id, fkSkipSql: true }
      subject:       { type: varchar, size: 255, required: true }
      body:          { type: longvarchar, required: true }
      is_rich:       { type: boolean, default: false }
      is_read:       { type: boolean, default: false }
      is_replied:    { type: boolean, default: false }
      is_forwarded:  { type: boolean, default: false }
      is_marked:     { type: boolean, default: false }
      is_deleted:    { type: boolean, default: false }
      created_at:    ~



  PrivateMessageTemplate:
    columns:
      id:  ~
      subject:      { type: varchar, size: 255, required: true }
      body:         { type: longvarchar, required: true }
      description:  { type: varchar, size: 255 }

    propel_behaviors:
      timestampable:  ~

  Comment:
    columns:
      id:  ~
      disqus_id:       { type: char, size: 10 }
      parent_id:       { type: char, size: 10 }
      collection_id:   { type: integer, foreignClass: Collection, foreignReference: id, required: true, onDelete: cascade }
      collectible_id:  { type: integer, foreignClass: Collectible, foreignReference: id, onDelete: setnull }
      collector_id:    { type: integer, foreignClass: Collector, foreignReference: id, onDelete: cascade }
      author_name:     { type: varchar, size: 128 }
      author_email:    { type: varchar, size: 128 }
      author_url:      { type: varchar, size: 255 }
      subject:         { type: varchar, size: 128 }
      body:            { type: longvarchar, required: true }
      ip_address:      { type: varchar, size: 15 }
      created_at:  ~

    uniques:
      comment_U_1:  [disqus_id]

    propel_behaviors:
      archivable: { archive_class: CommentArchive, archived_at_column: archived_at }

  CustomField:
    columns:
      id:  ~
      name:        { type: varchar, size: 64, required: true }
      type:        { type: tinyint, required: true }
      object:      longvarchar
      validation:  longvarchar

  CustomValue:
    columns:
      id:  ~
      collection_id:    { type: integer, foreignClass: Collection, foreignReference: id, required: true, onDelete: cascade }
      collectible_id:   { type: integer, foreignClass: Collectible, foreignReference: id, required: true, onDelete: cascade }
      field_id:         { type: integer, required: true }
      value_text:       varchar(255)
      value_date:       date
      value_numeric:    float
      value_bool:       { type: boolean, default: false }

    propel_behaviors:
      timestampable:  ~

  Event:
    columns:
      id:  ~
      title:        { type: varchar, size: 128, required: true }
      description:  { type: longvarchar, required: true }
      created_at:   ~

  EventVideo:
    columns:
      id:  ~
      event_id:  ~
      title:        { type: varchar, size: 128, required: true }
      description:  { type: longvarchar, required: true }
      lenght:       integer
      thumb_small:  varchar(255)
      thumb_large:  varchar(255)
      filename:     varchar(255)
      views:        integer
      created_at:   ~

  Video:
    columns:
      id:  ~
      title:         { type: varchar, size: 64, required: true }
      slug:          { type: varchar, size: 64 }
      description:   { type: longvarchar, required: true }
      type:          { type: varchar, size: 64, required: true }
      length:        integer
      filename:      varchar(128)
      thumb_small:   varchar(128)
      thumb_large:   varchar(128)
      is_published:  boolean
      published_at:  timestamp
      uploaded_at:   timestamp
      created_at:    ~

  VideoPlaylist:
    columns:
      id:  ~
      video_id:  ~
      playlist_id:  ~
      position:     tinyint

  VideoCollectionCategory:
    columns:
      id:  ~
      video_id:  ~
      collection_category_id:  { type: integer, required: true, foreignClass: CollectionCategory, foreignReference: id, onDelete: cascade }
      created_at:  ~

  Playlist:
    columns:
      id:  ~
      title:         { type: varchar, size: 64, required: true }
      slug:          { type: varchar, size: 64 }
      description:   { type: longvarchar, required: true }
      type:          { type: varchar, size: 64, required: true }
      length:        integer
      is_published:  boolean
      published_at:  timestamp
      created_at:    ~

  Trivia:
    columns:
      id:  ~
      content:     { type: longvarchar, required: true }
      created_at:  ~

  ResourceCategory:
    columns:
      id:          ~
      name:        { type: varchar, size: 128, required: true }
      slug:        varchar(128)
      thumbnail:   varchar(64)
      created_at:  ~

  ResourceEntry:
    columns:
      id:  ~
      category_id:  { type: integer, required: true, foreignClass: ResourceCategory, foreignReference: id }
      type:         { type: varchar, size: 24, required: true, default: Blog }
      name:         { type: varchar, size: 128, required: true }
      slug:         varchar(128)
      description:  { type: longvarchar, required: true }
      url:          { type: varchar, size: 255, required: true }
      rss:          { type: varchar, size: 255, required: true }
      thumbnail:    varchar(64)
      blogger:      varchar(128)
      email:        varchar(128)
      created_at:   ~

  Term:
    columns:
      id:  ~
      name:  { type: varchar, size: 100, primaryString: true }

  TermRelationship:
    columns:
      id:  ~
      term_id:   ~
      model:     { type: varchar, size: 30, index: true }
      model_id:  { type: integer }

  Score:
    columns:
      id:  ~
      day:         { type: date }
      model:       { type: char, size: 64, required: true }
      model_id:    { type: integer }
      views:       { type: integer, default: 0 }
      ratings:     { type: integer, default: 0 }
      score:       { type: integer, default: 0 }

    uniques:
      score_U_1:  [day, model, model_id]

    propel_behaviors:
      timestampable:  ~

  Featured:
    treeMode: NestedSet
    columns:
      id:  ~
      featured_type_id:  { type: tinyint, required: true }
      featured_model:    { type: varchar, size: 64, required: true }
      featured_id:       { type: integer }
      tree_left:         { type: integer, required: true, default: 0, nestedSetLeftKey: true }
      tree_right:        { type: integer, required: true, default: 0, nestedSetRightKey: true }
      tree_scope:        { type: integer, required: true, default: 0, treeScopeKey: true }
      eblob:             { type: longvarchar }
      start_date:        { type: date }
      end_date:          { type: date }
      position:          { type: tinyint, default: 0 }
      is_active:         { type: boolean, default: true, required: true }

  NewsletterSignup:
    columns:
      id:  ~
      email:  { type: varchar, size: 255, required: true }
      name:   { type: varchar, size: 255, required: true }
