generator:
  class: IcePropelGenerator
  param:
    model_class:           PrivateMessage
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              PrivateMessage
    plural:                PrivateMessages
    route_prefix:          private_message
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Messages
        display: [sender, receiver, subject, is_read, is_replied, is_deleted, created_at]
        sort: [created_at, desc]
      filter:
        display: [subject, body]
      form:    ~
      edit:    ~
      new:     ~
