all:
  stylesheets: [frontend/shopping-cart.css]
  components:
    sidebar_300: [shopping, sidebar]

checkoutPaypal:
  has_layout:  false

orderShippingSuccess:
  components:
    header:  [global, headerStripped]
    footer:  []
    sidebar_300: [shopping, sidebarCheckout]
    slot1:   [shopping, slot1Shipping]

orderPaySuccess:
  components:
    header:  [global, headerStripped]
    footer:  []
    sidebar_300: [shopping, sidebarCheckout]

paypalRedirect:
  has_layout:  false
