all:
  stylesheets: [frontend/modules/shopping.css]
  components:
    sidebar_300: [shopping, sidebar]

checkoutPaypal:
  has_layout:  false

orderShippingSuccess:
  components:
    header:  [global, headerStripped]
    footer:  []
    breadcrumbs: []
    # slot1:   [shopping, slot1Shipping]
    sidebar_300: [shopping, sidebarCheckout]

orderPaySuccess:
  layout: layout-minimal

orderReviewSuccess:
  components:
    footer:  []
    sidebar_300: [shopping, sidebarSignup]

paypalRedirect:
  has_layout:  false
