all:
  stylesheets: [frontend/modules/shopping.css]
  components:
    sidebar_300: [shopping, sidebar]

checkoutPaypal:
  has_layout:  false

orderShippingSuccess:
  components:
    header:  [global, headerStripped]
    footer:  []
    breadcrumbs: []
    slot1:   [shopping, slot1Shipping]
    sidebar_300: [shopping, sidebarCheckout]

orderPaySuccess:
  components:
    header:  [global, headerStripped]
    footer:  []
    sidebar_300: [shopping, sidebarCheckout]

paypalRedirect:
  has_layout:  false
