generator:
  class: IcePropelGenerator
  param:
    model_class:           Collector
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              Collector
    plural:                Collectors
    route_prefix:          collector
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~

      fields:
        id: { label: ID }
        list_username: { label: Username }
        list_email: { label: Email }
        display_name: { label: Display Name }
        list_count_collections: { label: Collections }
        list_spaminess: { label: Spaminess }
        list_auto_login: { label: '' }
        created_at: { label: Since, date_format: 'MM/dd/yyyy' }
        is_public: { label: "Public?" }
        list_newsletter: { label: '<i class="icon-envelope"></i>' }
        list_avatar: { label: "" }

      list:
        title: Collectors
        display:
          - id
          - _list_avatar
          - _list_username
          - display_name
          - _list_email
          - _list_newsletter
          - _list_count_collections
          - _list_spaminess
          - created_at
        sort: [created_at, desc]
        object_actions:
          _edit: ~
          _delete: ~
          autologin: { label: "Auto Login", action: autoLogin, params: { target: '_blank' } }
          markAsSpam: { label: "Mark as spam", action: markAsSpam, params: { confirm: "Are you sure you want to mark as spam this collector?" } }
          markAsHam: { label: "Mark as ham", action: markAsHam, params: { confirm: "Are you sure you want to mark as ham this collector?" } }
          togglePostingTimeouts: { label: "Toggle posting timeouts" }
          spamAndDestroy: { label: "Spam & Destroy", params: { confirm: "This will mark the collector as spam and DELETE him. Are you sure?" } }
          encourageSeller: { label: 'Send a "become seller" email' }
        actions:
          mailchimp: { label: "Sync with MailChimp.com", action: syncWithMailChimp }
          export: { label: "Export to CSV", sf_format: csv }

      filter:
        class: BackendCollectorFormFilter
        display: [username, display_name, email, user_type, spaminess, is_spam, newsletter, collection_id, created_at, secret_sale]
        fields:
          email:
            widgetOptions: { with_empty: false }
          spaminess: { label: Spaminess }
          is_spam: { label: "Spam?" }
          collection_id: { label: "Collection #" }
          created_at: { label: 'Member Since' }

      form:
        class: CollectorEditForm
        fields:
          is_public:
            attributes: { class: yes_no }

      edit:
        title: Edit Collector <small>(%%USERNAME%%)</small>
        fields:
          password: { label: Password, help: "If you do not want to change the password, leave the field empty" }
        display: [display_name, email, password, photo, is_public]

      new: ~
      export:
        sort: [id, asc]
        fields:
          count_collections: { label: Collections }
        display: [id, username, display_name, email, count_collections, count_collectibles, created_at]
