generator:
  class: IcePropelGenerator
  param:
    model_class:           wpPost
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              wpPost
    plural:                wpPosts
    route_prefix:          wp_post
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions:
        list: ~
        query_methods: [joinWithwpUser]

      fields:
        wp_user:  { label: Author, is_sortable: true }
        post_date: { label: Publish Date }
        count_words: { label: "# Words" }
        count_chars: { label: "# Chars" }

      list:
        title: Blog Posts
        display: [ wp_user, _post_title, _count_words, _count_chars, post_date ]
        actions: { }
        batch_actions: { }
        object_actions: { }
        sort: [ post_date, desc ]
        query_methods:
          filterByPublishedOrDraft: []
          filterByPostType:  ['post']

      filter:
        display: [ post_author, post_date, post_status, post_title, post_content ]

      form:    ~
      edit:    ~
      new:     ~
