#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "${SOURCE}" ] ; do SOURCE="$(readlink "${SOURCE}")"; done
DIR="$( cd -P "$( dirname "${SOURCE}" )" && pwd )"

br=`git branch | grep "*"`
[[ $1 != '' ]] && branch=$1 || branch=${br/* /}

cd ${DIR}/.. && git pull --recurse-submodules --ff-only origin ${branch}
cd ${DIR}/.. && git submodule update --recursive
cd ${DIR}/.. && exec watchr -l apps/frontend/config/less.watchr
cd ${DIR}/.. && php symfony cache:clear
