#!/bin/bash

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

[[ $1 != '' ]] && branch=$1 || branch="develop"

git pull --ff-only origin $branch
cd $DIR/.. && exec watchr -l apps/frontend/config/less.watchr
cd $DIR/.. && php symfony cache:clear
