generator:
  class: IcePropelGenerator
  param:
    model_class:           CollectibleForSale
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              CollectibleForSale
    plural:                CollectibleForSales
    route_prefix:          collectible_for_sale
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        created_at: { label: Date, date_format: 'MM/dd/yyyy' }
        marked_for_sale_at: { label: "For sale from" , date_format: 'MM/dd/yyyy' }

      list:
        title: Items for Sale
        fields:
          list_seller: { label: Seller }
          list_collectible: { label: Item }
          list_price: { label: Price }
        display: [_list_seller, _list_collectible, _list_price, condition, created_at, marked_for_sale_at]
        object_actions: {}
        batch_actions: {}
        actions:
          export: { label: 'Export to CSV', sf_format: csv }

      filter:
        display: [price, condition, created_at, marked_for_sale_at]

      form:
        display: [collectible_id, condition, is_ready, quantity]
      edit:    ~
      new:     ~

      export:
        fields:
          tag_string: { label: Tags }
          list_price: { label: Price }
          created_at: { label: Date }
          list_url: { label: Url }
        display: [name, _description, category, tag_string, _list_price, collector, created_at, condition, _list_url]
