generator:
  class: IcePropelGenerator
  param:
    model_class:           CollectibleForSale
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              CollectibleForSale
    plural:                CollectibleForSales
    route_prefix:          collectible_for_sale
    with_propel_route:     1
    actions_base_class:    cqBackendActions

    config:
      actions: ~
      fields:
        created_at: { label: Date, date_format: 'MM/dd/yyyy' }
        marked_for_sale_at: { label: Market Date , date_format: 'MM/dd/yyyy' }

      list:
        title: Items for Sale
        fields:
          list_seller: { label: Seller }
          list_thumbnail: { label: Thumbnail }
          list_collectible: { label: Name }
          list_price: { label: Price }
        display:
          - _list_seller
          - _list_thumbnail
          - _list_collectible
          - _list_price
          - condition
          - marked_for_sale_at
          - created_at
        object_actions: {}
        batch_actions: {}
        actions:
          export: { label: 'Export to CSV', sf_format: csv }

      filter:
        display: [price, condition, marked_for_sale_at, created_at]

      form:
        display: [collectible_id, condition, is_ready, quantity]
      edit:    ~
      new:     ~

      export:
        fields:
          category_path: { label: Category }
          tag_string: { label: Tags }
          list_price: { label: Price }
          created_at: { label: Date }
          list_url: { label: Link }
        display:
          - collectible_id
          - collector
          - category_path
          - name
          - _description
          - tag_string
          - _list_price
          - condition
          - marked_for_sale_at
          - _list_url
