all:
  stylesheets: [frontend/modules/mycq.css, -frontend/responsive.css]

  javascripts:
    - /assets/js/wysihtml5.js
    - /assets/js/bootstrap/wysihtml5.js
    - /assets/js/bootstrap/collapse.js
    - /assets/js/jquery/chosen.js

    - jquery/columnview.js
    - jquery/tmpl.js
    - jquery/iframe-transport.js
    - jquery/load-image.js
    - jquery/canvas-to-blob.js
    - jquery/fileupload.js
    - jquery/fileupload-fp.js
    - jquery/fileupload-ui.js
    - jquery/tagedit.js
    - jquery/autogrow-input.js

  components:
    slot1: [mycq, navigation]
    mycq_upload_photos: []
    mycq_dropbox: []

collectionsSuccess:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]

collectionCollectibles:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]

collectionDetails:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]

collectibleSuccess:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]

marketplaceSuccess:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]

collectibleWizardSuccess:
  components:
    mycq_upload_photos: [mycq, uploadPhotos]
    mycq_dropbox: [mycq, dropbox]