all:
  stylesheets: [frontend/modules/mycq.css]
  javascripts:
    - jquery/ui.js
    - jquery/easing.js
    - jquery/hoverIntent.js
    - jquery/controls.js
    - jquery/form.js
    - jquery/tmpl.js
    - jquery/iframe-transport.js
    - jquery/load-image.js
    - jquery/canvas-to-blob.js
    - jquery/fileupload.js
    - jquery/fileupload-fp.js
    - jquery/fileupload-ui.js
    - /assets/js/bootstrap/dialog2.js
    - /assets/js/bootstrap/dialog2.helpers.js

  components:
    slot1: [mycq, navigation]
