generator:
  class: IcePropelGenerator
  param:
    model_class:           iceModelMultimedia
    theme:                 bootstrap
    non_verbose_templates: true
    with_show:             false
    singular:              Multimedia
    plural:                Multimedias
    route_prefix:          multimedia
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        id: { label: ID }
        model: { label: Model }
        type: { label: Type }
        created_at: { label: Created At, date_format: 'MM/dd/yyyy' }
      list:
        title: Multimedia
        display:
          - id
          - model
          - type
          - created_at
        sort: [created_at, desc]
        object_actions:
          _edit: ~
          _delete: ~
          crop: { label: "Crop", action: crop }
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
