generator:
  class: sfPropelGenerator
  param:
    model_class:           Multimedia
    theme:                 admin15
    non_verbose_templates: true
    with_show:             false
    singular:              Multimedia
    plural:                Multimedias
    route_prefix:          multimedia
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
